// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by gears2fsm from ./pr.gears.md.
import { assign, fromPromise, setup } from 'xstate';
import { validatePlaybookCallResult } from '@sublang/playbook/xstate-runtime';
/** No parallel group: the playbook runs one delegated role at a time. */
export const concurrentRoleSets = [];
const CALLER_INPUT_PLACEHOLDER = '<caller-input>';
const PULL_REQUEST_URL_PLACEHOLDER = '<pull-request-url>';
/** The one nested target, shared by `invoke.input` and result validation. */
const CODE_PLAYBOOK_ID = 'code';
const OPEN_PULL_REQUEST_PROMPT = [
    'Publish the branch and open its pull request without changing any file or making any commit.',
    'Confirm that the working tree is clean and that the checked-out branch is the branch to deliver, not the repository default branch.',
    "Push the branch to the repository's GitHub remote with its upstream set; never force-push.",
    'If an open pull request for this branch already exists, use it; otherwise open one against the repository default branch with `gh pr create`.',
    'Give the pull request a title naming the change and a body with a summary of what changed and why from the base revision to the last commit, the verification the commits report, and a `Closes #N` line for issue number N when the request names one.',
    'Report the pull request number and URL exactly.',
    'If the working tree is not clean, the checked-out branch is wrong, the push is rejected, or the pull request cannot be opened, open nothing further and report the failure with its reason.',
    '',
    '> Original request: <caller-input>',
].join('\n');
const OPEN_PULL_REQUEST_RESULTS = {
    opened: "Coder's result affirmatively supports that the pull request is open. Output shall include `pullRequest: <exact pull request number as reported>` and `pullRequestUrl: <exact pull request URL as reported>`.",
    notPublished: "Coder's result affirmatively supports that the branch or its pull request was not published; the workflow fails and returns Coder's complete result with its reason to its caller. Output shall include `coderOutput: <verbatim final text>`.",
    needsBossReply: "The acting agent's prose surfaces a clarifying question for Boss that the agent cannot answer alone. Output shall include `question: <verbatim question text from the acting agent's prose>`.",
};
const CHECK_WAIT_COMMAND = [
    `n=0`,
    `while gh pr checks 2>&1 | grep -q 'no checks reported'; do`,
    `n=$((n + 1))`,
    `[ "$n" -ge 6 ] && exit 0`,
    `sleep 10`,
    `done`,
    `gh pr checks --watch --fail-fast >/dev/null 2>&1`,
].join('\n');
const WAIT_FOR_CHECKS_RESULTS = {
    checksPassed: 'The command exited with status zero: the checks passed; a pull request whose repository still reports no checks after a brief wait for them to register counts as passed.',
    checksFailed: 'The command exited with a nonzero status: the checks failed.',
};
const PUBLISH_FIX_COMMAND_TEMPLATE = [
    `[ "$(gh pr view --json url --jq .url)" = '<pull-request-url>' ] || exit 1`,
    `git push || exit 1`,
    `n=0`,
    `until [ "$(gh pr view --json headRefOid --jq .headRefOid 2>/dev/null)" = "$(git rev-parse HEAD)" ]; do`,
    `n=$((n + 1))`,
    `[ "$n" -ge 12 ] && exit 1`,
    `sleep 5`,
    `done`,
].join('\n');
const PUBLISH_FIX_RESULTS = {
    fixPublished: "The command exited with status zero, once the pull request's head is the pushed commit: the fix is published.",
    fixNotPublished: 'The command exited with a nonzero status: the fix is not published, an authored failure of the workflow that leaves the pull request open.',
};
const WAIT_FOR_FIX_CHECKS_RESULTS = {
    checksPassed: 'The command exited with status zero: the checks passed.',
    checksStillFailing: 'The command exited with a nonzero status: the checks are still failing, an authored failure of the workflow that leaves the pull request open; there is no second fix attempt.',
};
const MERGE_COMMAND_TEMPLATE = [
    `pr=$(gh pr view --json url --jq .url) || exit 1`,
    `[ "$pr" = '<pull-request-url>' ] || exit 1`,
    `base=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name) || exit 1`,
    `[ -n "$base" ] || exit 1`,
    `[ "$(gh pr view "$pr" --json baseRefName --jq .baseRefName)" = "$base" ] || exit 1`,
    `gh pr merge --merge --delete-branch --match-head-commit "$(git rev-parse HEAD)" || exit 1`,
    `[ "$(gh pr view "$pr" --json state --jq .state)" = MERGED ] || exit 1`,
    `[ "$(git branch --show-current)" = "$base" ]`,
].join('\n');
const MERGE_RESULTS = {
    merged: 'The command exited with status zero: the pull request is merged.',
    mergeRefused: 'The command exited with a nonzero status: the merge is refused, an authored failure of the workflow that leaves the pull request in the state GitHub reports, because the checkout no longer infers the published pull request, the pull request targets another branch, GitHub refused the merge for a conflict, a branch protection, a forbidden merge method, or a head that moved, or the merge may have landed while its confirmation, the local switch to the default branch, or the branch deletion failed; a refused merge does not establish that the pull request is unmerged, so the workflow reports it as an unconfirmed merge rather than as not merged.',
};
const LOCAL_UPDATE_COMMAND = `git pull --ff-only`;
const LOCAL_UPDATE_RESULTS = {
    localDefaultUpdated: 'The command exited with status zero: the local default branch is updated; the workflow completes, returning the pull request number and URL, the fact that the pull request is merged, and that the local default branch was fast-forwarded to the merged head.',
    localDefaultNotUpdated: 'The command exited with a nonzero status: the local default branch is not updated; the workflow completes, since the pull request is merged either way, returning the pull request number and URL, the fact that the pull request is merged, and that the local default branch was not fast-forwarded to the merged head.',
};
const FIX_CODING_REQUEST = "The pull request's checks are red on the checked-out branch. Inspect the failing checks with `gh pr checks` and `gh run view --log-failed`, fix their cause on this branch with a minimal change, and make the checks pass.";
const STATE_DESCRIPTIONS = {
    ready: 'Waiting for a reviewed branch to deliver through a pull request.',
    openPullRequest: 'Coder is publishing the branch and opening its pull request without changing any file or making any commit.',
    awaitBossReply: "Waiting for Boss to answer the acting agent's question.",
    waitForChecks: "Waiting for the pull request's checks before any fix attempt.",
    fixChecks: "The CODE playbook is making the one fix attempt for the pull request's failing checks.",
    publishFix: 'Pushing the fix to the published pull request and waiting until its head is the pushed commit.',
    waitForFixChecks: "Waiting for the pull request's checks after the one fix attempt.",
    mergePullRequest: 'Merging the published pull request into the repository default branch and confirming the merge.',
    updateLocalDefault: 'Fast-forwarding the local default branch to the merged head.',
    failed: 'The pull-request workflow failed outside its authored outcomes and is waiting for a new delivery request.',
    mergedLocalUpdated: 'The pull request is merged and the local default branch was fast-forwarded to the merged head.',
    mergedLocalNotUpdated: 'The pull request is merged, but the local default branch was not fast-forwarded to the merged head.',
    notPublished: "The branch or its pull request was not published; the workflow failed with Coder's complete result and its reason.",
    fixFailed: "The one CODE fix attempt ended in an authored abort or failure, or a terminal result that did not prove its success; the workflow failed relaying that result and left the pull request open.",
    fixNotPublished: 'The fix was not published; the workflow failed and left the pull request open.',
    checksFailed: 'The checks are still failing after the one fix attempt; the workflow failed and left the pull request open.',
    mergeUnconfirmed: 'The merge was refused or could not be confirmed; the workflow failed with an unconfirmed merge, leaving the pull request in the state GitHub reports.',
};
function playbookMeta(stateId, role) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            ...(role === undefined ? {} : { role }),
        },
    };
}
function terminalMeta(stateId, terminal) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            terminal,
        },
    };
}
function isRecord(value) {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
        return false;
    }
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
}
function isNonEmptyString(value) {
    return typeof value === 'string' && value.trim().length > 0;
}
function isCanonicalIndex(key, length) {
    return /^(0|[1-9][0-9]*)$/.test(key) && Number(key) < length;
}
/** Strict JSON validation; tracks only the active recursion path. */
function isJsonValue(value, path = new Set()) {
    if (value === null)
        return true;
    switch (typeof value) {
        case 'boolean':
        case 'string':
            return true;
        case 'number':
            return Number.isFinite(value);
        case 'object':
            break;
        default:
            return false;
    }
    const container = value;
    if (path.has(container))
        return false;
    path.add(container);
    try {
        if (Array.isArray(container)) {
            if (Object.getPrototypeOf(container) !== Array.prototype)
                return false;
            const length = container.length;
            const keys = Reflect.ownKeys(container);
            if (keys.length !== length + 1)
                return false;
            for (const key of keys) {
                if (typeof key !== 'string')
                    return false;
                const descriptor = Object.getOwnPropertyDescriptor(container, key);
                if (descriptor === undefined || !('value' in descriptor))
                    return false;
                if (key === 'length') {
                    if (descriptor.enumerable || descriptor.configurable)
                        return false;
                    if (descriptor.value !== length)
                        return false;
                    continue;
                }
                if (!isCanonicalIndex(key, length) || !descriptor.enumerable) {
                    return false;
                }
                if (!isJsonValue(descriptor.value, path))
                    return false;
            }
            return true;
        }
        if (!isRecord(container))
            return false;
        for (const key of Reflect.ownKeys(container)) {
            if (typeof key !== 'string')
                return false;
            const descriptor = Object.getOwnPropertyDescriptor(container, key);
            if (descriptor === undefined ||
                !descriptor.enumerable ||
                !('value' in descriptor)) {
                return false;
            }
            if (!isJsonValue(descriptor.value, path))
                return false;
        }
        return true;
    }
    finally {
        path.delete(container);
    }
}
function normalizeError(error) {
    if (error instanceof Error) {
        return {
            name: error.name || 'Error',
            message: error.message,
            ...(typeof error.stack === 'string' ? { stack: error.stack } : {}),
        };
    }
    return { name: 'Error', message: String(error) };
}
/** Binds a value as its own single-quoted shell literal. */
function shellLiteral(value) {
    return `'${value.split("'").join("'\\''")}'`;
}
/**
 * Replaces the single-quoted `'<pull-request-url>'` shell word, quotes
 * included, with the bound literal; an absent value keeps the placeholder.
 */
function bindPullRequestUrl(template, context) {
    const url = context.pullRequestUrl;
    if (url === undefined)
        return template;
    return template
        .split(`'${PULL_REQUEST_URL_PLACEHOLDER}'`)
        .join(shellLiteral(url));
}
/** Quoted relay: empty values add no line; multi-line values quote each line. */
function quotedRelay(values) {
    return values
        .filter(([, value]) => value.length > 0)
        .map(([label, value]) => `${label}: ${value}`
        .split('\n')
        .map((line) => `> ${line}`)
        .join('\n'))
        .join('\n');
}
function fixCallText(context) {
    return quotedRelay([
        ['Original request', context.callerInput ?? CALLER_INPUT_PLACEHOLDER],
        ['Pull request', context.pullRequestUrl ?? PULL_REQUEST_URL_PLACEHOLDER],
        ['Coding request', FIX_CODING_REQUEST],
    ]);
}
function actorOutput(event) {
    if (!isRecord(event))
        return undefined;
    return isRecord(event.output) ? event.output : undefined;
}
function outputString(event, field) {
    const value = actorOutput(event)?.[field];
    return isNonEmptyString(value) ? value : undefined;
}
function playerGuard(event, guard) {
    return actorOutput(event)?.guard === guard;
}
function isOpened({ event }) {
    return (playerGuard(event, 'opened') &&
        outputString(event, 'pullRequest') !== undefined &&
        outputString(event, 'pullRequestUrl') !== undefined);
}
function isNotPublished({ event }) {
    return (playerGuard(event, 'notPublished') &&
        outputString(event, 'coderOutput') !== undefined);
}
function needsBossReply({ event }) {
    return (playerGuard(event, 'needsBossReply') &&
        outputString(event, 'question') !== undefined);
}
/** Script outcome: the declared guard, consistent with its exit status. */
function scriptOutcome(guard, exit) {
    return ({ event }) => {
        const output = actorOutput(event);
        if (output === undefined || output.guard !== guard)
            return false;
        const status = output.exitStatus;
        if (typeof status !== 'number' || !Number.isInteger(status))
            return false;
        return exit === 'zero' ? status === 0 : status !== 0;
    };
}
function childOutputOf(event) {
    return isRecord(event) ? event.output : undefined;
}
/**
 * The public success variant of the `code` output interface: CODE completed
 * with every review passed, naming its last commit and evaluated revision.
 */
function isCodeSuccess({ event }) {
    const output = childOutputOf(event);
    return (isRecord(output) &&
        output.status === 'complete' &&
        isNonEmptyString(output.lastCodeCommit) &&
        isNonEmptyString(output.finalEvaluatedRevision) &&
        output.allReviewsPassed === true);
}
/** A delivered CODE result that does not prove success, as valid JSON. */
function isInsufficientCodeResult({ event }) {
    const output = childOutputOf(event);
    return output === undefined || isJsonValue(output);
}
export function authoredChildResult(error, expectedPlaybookId) {
    if (!(error instanceof Error))
        return undefined;
    try {
        const result = validatePlaybookCallResult(error.result, expectedPlaybookId);
        return result.status !== 'ok' || result.terminal?.kind === 'failure'
            ? result
            : undefined;
    }
    catch {
        return undefined;
    }
}
function eventError(event) {
    return isRecord(event) ? event.error : undefined;
}
function isAuthoredCodeFailure({ event }) {
    return authoredChildResult(eventError(event), CODE_PLAYBOOK_ID) !== undefined;
}
function relayedCodeResult(event) {
    const result = authoredChildResult(eventError(event), CODE_PLAYBOOK_ID);
    if (result === undefined)
        return undefined;
    if (result.status === 'ok') {
        return {
            playbookId: CODE_PLAYBOOK_ID,
            status: 'ok',
            ...(result.output === undefined ? {} : { output: result.output }),
        };
    }
    const error = result.error === undefined
        ? {
            name: 'AbortError',
            message: `${CODE_PLAYBOOK_ID.toUpperCase()} was aborted.`,
        }
        : { name: result.error.name, message: result.error.message };
    return { playbookId: CODE_PLAYBOOK_ID, status: result.status, error };
}
function insufficientCodeResult(event) {
    const output = childOutputOf(event);
    return {
        playbookId: CODE_PLAYBOOK_ID,
        status: 'ok',
        ...(output === undefined || !isJsonValue(output)
            ? {}
            : { output: output }),
    };
}
function resumableStates(ids) {
    return ids.map((id) => ({
        guard: ({ context, event }) => event.type === 'BOSS_REPLY' &&
            event.answer.trim().length > 0 &&
            context.pendingBossQuestion?.resumeStateId === id &&
            (event.questionId === undefined || event.questionId === id),
        target: `#${id}`,
        reenter: true,
        actions: 'rememberBossReply',
    }));
}
const machineSetup = setup({
    types: {},
    actors: {
        player: fromPromise(async () => {
            throw new Error('player actor must be provided by the runner');
        }),
        playbook: fromPromise(async () => {
            throw new Error('playbook actor must be provided by the runner');
        }),
        script: fromPromise(async () => {
            throw new Error('script actor must be provided by the runner');
        }),
    },
    guards: {
        validStartPr: ({ event }) => event.type === 'START_PR' && isNonEmptyString(event.callerInput),
        isOpened,
        isNotPublished,
        needsBossReply,
        emptyBossReply: ({ event }) => event.type === 'BOSS_REPLY' && event.answer.trim().length === 0,
        waitForChecksPassed: scriptOutcome('checksPassed', 'zero'),
        waitForChecksFailed: scriptOutcome('checksFailed', 'nonzero'),
        isCodeSuccess,
        isInsufficientCodeResult,
        isAuthoredCodeFailure,
        fixPublished: scriptOutcome('fixPublished', 'zero'),
        fixNotPublished: scriptOutcome('fixNotPublished', 'nonzero'),
        waitForFixChecksPassed: scriptOutcome('checksPassed', 'zero'),
        checksStillFailing: scriptOutcome('checksStillFailing', 'nonzero'),
        merged: scriptOutcome('merged', 'zero'),
        mergeRefused: scriptOutcome('mergeRefused', 'nonzero'),
        localDefaultUpdated: scriptOutcome('localDefaultUpdated', 'zero'),
        localDefaultNotUpdated: scriptOutcome('localDefaultNotUpdated', 'nonzero'),
    },
    actions: {
        'playbook.acceptedOutcome': (_args, _params) => undefined,
        startPr: assign(({ event }) => {
            if (event.type !== 'START_PR')
                return {};
            return {
                callerInput: event.callerInput,
                pullRequest: undefined,
                pullRequestUrl: undefined,
                coderOutput: undefined,
                childResult: undefined,
                localDefaultUpdated: undefined,
                completion: undefined,
                lastError: undefined,
                pendingBossQuestion: undefined,
                bossReply: undefined,
            };
        }),
        rememberOpened: assign(({ event }) => ({
            pullRequest: outputString(event, 'pullRequest'),
            pullRequestUrl: outputString(event, 'pullRequestUrl'),
        })),
        completeNotPublished: assign(({ event }) => ({
            coderOutput: outputString(event, 'coderOutput'),
            completion: 'not-published',
        })),
        setPendingBossQuestion: assign(({ event }) => {
            const question = outputString(event, 'question');
            if (question === undefined)
                return {};
            const pending = {
                questionId: 'openPullRequest',
                resumeStateId: 'openPullRequest',
                sourceItem: 'PR-1',
                asker: { kind: 'role', roleId: 'coder' },
                question,
            };
            return { pendingBossQuestion: pending, bossReply: undefined };
        }),
        clearBossReplyContext: assign({
            pendingBossQuestion: undefined,
            bossReply: undefined,
        }),
        rememberBossReply: assign(({ event }) => event.type === 'BOSS_REPLY' ? { bossReply: event.answer } : {}),
        rememberEmptyBossReplyError: assign({
            lastError: () => ({
                name: 'Error',
                message: 'BOSS_REPLY received an empty answer',
            }),
            pendingBossQuestion: undefined,
            bossReply: undefined,
        }),
        completeWithCodeFailure: assign(({ event }) => {
            const childResult = relayedCodeResult(event);
            return childResult === undefined
                ? {}
                : { childResult, completion: 'fix-failed' };
        }),
        completeWithInsufficientCodeResult: assign(({ event }) => ({
            childResult: insufficientCodeResult(event),
            completion: 'fix-failed',
        })),
        completeFixNotPublished: assign({
            completion: 'fix-not-published',
        }),
        completeChecksFailed: assign({ completion: 'checks-failed' }),
        completeMergeUnconfirmed: assign({
            completion: 'merge-unconfirmed',
        }),
        completeMergedLocalUpdated: assign({
            completion: 'merged',
            localDefaultUpdated: true,
        }),
        completeMergedLocalNotUpdated: assign({
            completion: 'merged',
            localDefaultUpdated: false,
        }),
        rememberActorError: assign(({ event }) => ({
            lastError: normalizeError(eventError(event)),
        })),
        rememberMalformedPlayerOutput: assign({
            lastError: () => ({
                name: 'Error',
                message: 'Coder result for PR-1 did not match an available outcome.',
            }),
        }),
        rememberMalformedScriptOutput: assign({
            lastError: () => ({
                name: 'Error',
                message: 'Script result did not match its declared outcomes.',
            }),
        }),
        rememberMalformedChildOutput: assign({
            lastError: () => ({
                name: 'TypeError',
                message: 'CODE delivered output that is not JSON-safe.',
            }),
        }),
    },
});
function pullRequestIdentity(context) {
    if (!isNonEmptyString(context.pullRequest) ||
        !isNonEmptyString(context.pullRequestUrl)) {
        throw new Error('PR reached a final state without the reported pull request number and URL');
    }
    return {
        pullRequest: context.pullRequest,
        pullRequestUrl: context.pullRequestUrl,
    };
}
export const prMachine = machineSetup.createMachine({
    id: 'pr',
    initial: 'ready',
    context: {},
    output: ({ context }) => {
        switch (context.completion) {
            case 'merged': {
                if (typeof context.localDefaultUpdated !== 'boolean') {
                    throw new Error('PR reached merged without the local update fact');
                }
                return {
                    status: 'merged',
                    ...pullRequestIdentity(context),
                    localDefaultUpdated: context.localDefaultUpdated,
                };
            }
            case 'not-published': {
                if (!isNonEmptyString(context.coderOutput)) {
                    throw new Error("PR reached not-published without Coder's report");
                }
                return {
                    status: 'not-merged',
                    reason: 'not-published',
                    coderOutput: context.coderOutput,
                };
            }
            case 'fix-failed': {
                if (context.childResult === undefined) {
                    throw new Error('PR reached fix-failed without the CODE result');
                }
                return {
                    status: 'not-merged',
                    reason: 'fix-failed',
                    ...pullRequestIdentity(context),
                    childResult: context.childResult,
                };
            }
            case 'fix-not-published':
            case 'checks-failed':
                return {
                    status: 'not-merged',
                    reason: context.completion,
                    ...pullRequestIdentity(context),
                };
            case 'merge-unconfirmed':
                return {
                    status: 'merge-unconfirmed',
                    ...pullRequestIdentity(context),
                };
            default:
                throw new Error('PR reached a final state without a recorded completion');
        }
    },
    states: {
        ready: {
            id: 'ready',
            description: STATE_DESCRIPTIONS.ready,
            meta: playbookMeta('ready'),
            tags: ['playbook.parked'],
            on: {
                START_PR: {
                    guard: 'validStartPr',
                    target: 'openPullRequest',
                    actions: 'startPr',
                },
            },
        },
        openPullRequest: {
            id: 'openPullRequest',
            description: STATE_DESCRIPTIONS.openPullRequest,
            meta: playbookMeta('openPullRequest', 'coder'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'player',
                input: ({ context }) => ({
                    stateId: 'openPullRequest',
                    role: 'coder',
                    sourceItem: 'PR-1',
                    prompt: OPEN_PULL_REQUEST_PROMPT,
                    result: OPEN_PULL_REQUEST_RESULTS,
                    callerInput: context.callerInput ?? CALLER_INPUT_PLACEHOLDER,
                    ...(context.pendingBossQuestion === undefined
                        ? {}
                        : { pendingBossQuestion: context.pendingBossQuestion }),
                    ...(context.bossReply === undefined
                        ? {}
                        : { bossReply: context.bossReply }),
                }),
                onDone: [
                    {
                        guard: 'isOpened',
                        target: 'waitForChecks',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'openPullRequest',
                                    target: 'waitForChecks',
                                    acceptedOutcome: 'opened',
                                },
                            },
                            'rememberOpened',
                            'clearBossReplyContext',
                        ],
                    },
                    {
                        guard: 'isNotPublished',
                        target: 'notPublished',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'openPullRequest',
                                    target: 'notPublished',
                                    acceptedOutcome: 'notPublished',
                                },
                            },
                            'completeNotPublished',
                            'clearBossReplyContext',
                        ],
                    },
                    {
                        guard: 'needsBossReply',
                        target: 'awaitBossReply',
                        actions: [
                            {
                                type: 'playbook.acceptedOutcome',
                                params: {
                                    source: 'openPullRequest',
                                    target: 'awaitBossReply',
                                    acceptedOutcome: 'needsBossReply',
                                },
                            },
                            'setPendingBossQuestion',
                        ],
                    },
                    { target: 'failed', actions: 'rememberMalformedPlayerOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        awaitBossReply: {
            id: 'awaitBossReply',
            description: STATE_DESCRIPTIONS.awaitBossReply,
            meta: playbookMeta('awaitBossReply'),
            tags: ['playbook.parked'],
            on: {
                BOSS_REPLY: [
                    {
                        guard: 'emptyBossReply',
                        target: '#failed',
                        actions: 'rememberEmptyBossReplyError',
                    },
                    ...resumableStates(['openPullRequest']),
                ],
                START_PR: {
                    guard: 'validStartPr',
                    target: 'openPullRequest',
                    actions: 'startPr',
                },
            },
        },
        waitForChecks: {
            id: 'waitForChecks',
            description: STATE_DESCRIPTIONS.waitForChecks,
            meta: playbookMeta('waitForChecks'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'script',
                input: () => ({
                    stateId: 'waitForChecks',
                    sourceItem: 'PR-2',
                    command: CHECK_WAIT_COMMAND,
                    result: WAIT_FOR_CHECKS_RESULTS,
                }),
                onDone: [
                    { guard: 'waitForChecksPassed', target: 'mergePullRequest' },
                    { guard: 'waitForChecksFailed', target: 'fixChecks' },
                    { target: 'failed', actions: 'rememberMalformedScriptOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        fixChecks: {
            id: 'fixChecks',
            description: STATE_DESCRIPTIONS.fixChecks,
            meta: playbookMeta('fixChecks'),
            tags: ['playbook.suspended'],
            invoke: {
                src: 'playbook',
                input: ({ context }) => ({
                    stateId: 'fixChecks',
                    sourceItem: 'PR-3',
                    playbookId: CODE_PLAYBOOK_ID,
                    text: fixCallText(context),
                }),
                onDone: [
                    { guard: 'isCodeSuccess', target: 'publishFix' },
                    {
                        guard: 'isInsufficientCodeResult',
                        target: 'fixFailed',
                        actions: 'completeWithInsufficientCodeResult',
                    },
                    { target: 'failed', actions: 'rememberMalformedChildOutput' },
                ],
                onError: [
                    {
                        guard: 'isAuthoredCodeFailure',
                        target: 'fixFailed',
                        actions: 'completeWithCodeFailure',
                    },
                    { target: 'failed', actions: 'rememberActorError' },
                ],
            },
        },
        publishFix: {
            id: 'publishFix',
            description: STATE_DESCRIPTIONS.publishFix,
            meta: playbookMeta('publishFix'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'script',
                input: ({ context }) => ({
                    stateId: 'publishFix',
                    sourceItem: 'PR-4',
                    command: bindPullRequestUrl(PUBLISH_FIX_COMMAND_TEMPLATE, context),
                    result: PUBLISH_FIX_RESULTS,
                }),
                onDone: [
                    { guard: 'fixPublished', target: 'waitForFixChecks' },
                    {
                        guard: 'fixNotPublished',
                        target: 'fixNotPublished',
                        actions: 'completeFixNotPublished',
                    },
                    { target: 'failed', actions: 'rememberMalformedScriptOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        waitForFixChecks: {
            id: 'waitForFixChecks',
            description: STATE_DESCRIPTIONS.waitForFixChecks,
            meta: playbookMeta('waitForFixChecks'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'script',
                input: () => ({
                    stateId: 'waitForFixChecks',
                    sourceItem: 'PR-5',
                    command: CHECK_WAIT_COMMAND,
                    result: WAIT_FOR_FIX_CHECKS_RESULTS,
                }),
                onDone: [
                    { guard: 'waitForFixChecksPassed', target: 'mergePullRequest' },
                    {
                        guard: 'checksStillFailing',
                        target: 'checksFailed',
                        actions: 'completeChecksFailed',
                    },
                    { target: 'failed', actions: 'rememberMalformedScriptOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        mergePullRequest: {
            id: 'mergePullRequest',
            description: STATE_DESCRIPTIONS.mergePullRequest,
            meta: playbookMeta('mergePullRequest'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'script',
                input: ({ context }) => ({
                    stateId: 'mergePullRequest',
                    sourceItem: 'PR-6',
                    command: bindPullRequestUrl(MERGE_COMMAND_TEMPLATE, context),
                    result: MERGE_RESULTS,
                }),
                onDone: [
                    { guard: 'merged', target: 'updateLocalDefault' },
                    {
                        guard: 'mergeRefused',
                        target: 'mergeUnconfirmed',
                        actions: 'completeMergeUnconfirmed',
                    },
                    { target: 'failed', actions: 'rememberMalformedScriptOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        updateLocalDefault: {
            id: 'updateLocalDefault',
            description: STATE_DESCRIPTIONS.updateLocalDefault,
            meta: playbookMeta('updateLocalDefault'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'script',
                input: () => ({
                    stateId: 'updateLocalDefault',
                    sourceItem: 'PR-7',
                    command: LOCAL_UPDATE_COMMAND,
                    result: LOCAL_UPDATE_RESULTS,
                }),
                onDone: [
                    {
                        guard: 'localDefaultUpdated',
                        target: 'mergedLocalUpdated',
                        actions: 'completeMergedLocalUpdated',
                    },
                    {
                        guard: 'localDefaultNotUpdated',
                        target: 'mergedLocalNotUpdated',
                        actions: 'completeMergedLocalNotUpdated',
                    },
                    { target: 'failed', actions: 'rememberMalformedScriptOutput' },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        failed: {
            id: 'failed',
            description: STATE_DESCRIPTIONS.failed,
            meta: playbookMeta('failed'),
            tags: ['playbook.parked'],
            on: {
                START_PR: {
                    guard: 'validStartPr',
                    target: 'openPullRequest',
                    actions: 'startPr',
                },
            },
        },
        mergedLocalUpdated: {
            id: 'mergedLocalUpdated',
            description: STATE_DESCRIPTIONS.mergedLocalUpdated,
            meta: terminalMeta('mergedLocalUpdated', 'success'),
            type: 'final',
        },
        mergedLocalNotUpdated: {
            id: 'mergedLocalNotUpdated',
            description: STATE_DESCRIPTIONS.mergedLocalNotUpdated,
            meta: terminalMeta('mergedLocalNotUpdated', 'success'),
            type: 'final',
        },
        notPublished: {
            id: 'notPublished',
            description: STATE_DESCRIPTIONS.notPublished,
            meta: terminalMeta('notPublished', 'failure'),
            type: 'final',
        },
        fixFailed: {
            id: 'fixFailed',
            description: STATE_DESCRIPTIONS.fixFailed,
            meta: terminalMeta('fixFailed', 'failure'),
            type: 'final',
        },
        fixNotPublished: {
            id: 'fixNotPublished',
            description: STATE_DESCRIPTIONS.fixNotPublished,
            meta: terminalMeta('fixNotPublished', 'failure'),
            type: 'final',
        },
        checksFailed: {
            id: 'checksFailed',
            description: STATE_DESCRIPTIONS.checksFailed,
            meta: terminalMeta('checksFailed', 'failure'),
            type: 'final',
        },
        mergeUnconfirmed: {
            id: 'mergeUnconfirmed',
            description: STATE_DESCRIPTIONS.mergeUnconfirmed,
            meta: terminalMeta('mergeUnconfirmed', 'failure'),
            type: 'final',
        },
    },
});
export default prMachine;
