// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./decide.fsm.ts
// Role metadata: Coder→coder, Reviewer→reviewer (canonical local roles)
// Boss event:    deterministic START_DECIDE entry; exact Boss text becomes
//                callerTopic; pending player questions retain BOSS_REPLY,
//                keyed by question id while both proposal branches wait
// Parallel:      the independent-proposal pair runs through the shared
//                factory's parallel profile as one all-unchanged cohort
//                (DR-067)
// Adjudication:  LLM judge per state; coderProposal, reviewerProposal, and
//                coderOutput are carried verbatim; latestCommit is
//                receipt-owned effect evidence, never taken from prose
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  composePlayerContinuation,
  snapshotJsonValue,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeConstruction,
  type XStatePromptIdentity,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import {
  decideMachine,
  type DecideInput,
  type PlayerInput,
} from './decide.fsm.js';
import type { PlaybookHostConstructionCapabilities } from '../code.playbook/playbook-captain.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

export type DecidePlaybookOptions = DecideInput;
export type DecidePlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<DecidePlaybookOptions, object>['hostCapabilities'];

const PLACEHOLDER = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g;

const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'coderProposal',
  'reviewerProposal',
  'coderOutput',
]);
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([
  'reportedReviewFailure',
]);

function snapshotDecideOptions(value: unknown): DecidePlaybookOptions {
  const captured = snapshotJsonValue(value, 'DECIDE runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('DECIDE runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const key of Object.keys(record)) {
    throw new TypeError(`DECIDE runtime options.${key} is not declared`);
  }
  return captured as unknown as DecidePlaybookOptions;
}

function placeholderField(token: string): string {
  if (token === '#') return 'irNumber';
  return token.replace(/-([A-Za-z0-9_$])/g, (_match, next: string) =>
    next.toUpperCase(),
  );
}

function quotedContinuation(value: string): string {
  return value.replaceAll('\n', '\n> ');
}

/** Keep every line of a relayed runtime value inside its authored quote. */
function composePlayerPrompt(
  input: PlayerInput,
  promptIdentity: XStatePromptIdentity,
  resuming = false,
): string {
  const fields = input as unknown as Record<string, unknown>;
  const body = input.prompt.replace(
    PLACEHOLDER,
    (match: string, token: string, offset: number, source: string) => {
      const value =
        token === 'coder-llm'
          ? promptIdentity('coder')
          : token === 'reviewer-llm'
            ? promptIdentity('reviewer')
            : fields[placeholderField(token)];
      if (typeof value !== 'string') return match;
      const lineStart = source.lastIndexOf('\n', offset - 1) + 1;
      return source.slice(lineStart, offset).startsWith('> ')
        ? quotedContinuation(value)
        : value;
    },
  );
  return composePlayerContinuation(input, body, resuming);
}

export const _internal = {
  composePlayerPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'DECIDE',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotDecideOptions,
  entryEvent: {
    type: 'START_DECIDE',
    textField: 'callerTopic',
    // `copyStartTopic` copies the entry text here, so the failure-state
    // retry reads it back from the persisted machine snapshot and survives
    // a continued session (DR-034).
    contextField: 'callerTopic',
  },
  roleStates: {
    askCoderProposal: {
      role: 'coder',
      label: 'Coder independently proposes a spec design.',
    },
    askReviewerProposal: {
      role: 'reviewer',
      label: 'Reviewer independently proposes a spec design.',
    },
    commitCoderProposal: {
      role: 'coder',
      label: 'Coder synthesizes both proposals and commits the design.',
    },
  },
  outcomeAuthority: {
    governedPlayerStates: {
      askCoderProposal: {
        proposed: {
          fields: { coderProposal: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
      },
      askReviewerProposal: {
        proposed: {
          fields: { reviewerProposal: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'unchanged',
        },
      },
      commitCoderProposal: {
        committed: {
          fields: {
            coderOutput: 'presentation',
            latestCommit: 'effect',
          },
          repositoryDisposition: 'one-descendant-commit',
        },
        needsBossReply: {
          fields: { question: 'presentation' },
          repositoryDisposition: 'deferred',
        },
      },
    },
  },
  composePlayerPrompt: (
    input: PlaybookPlayerInput,
    promptIdentity: XStatePromptIdentity,
    resuming?: boolean,
  ) => composePlayerPrompt(input as PlayerInput, promptIdentity, resuming),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: [
    'callerTopic',
    'targetId',
    'bossIntent',
    'questionId',
    'answer',
  ],
} satisfies XStatePlaybookRuntimeSpecV3<DecidePlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    DecidePlaybookOptions,
    DecidePlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  DecidePlaybookOptions,
  DecidePlaybookHostCapabilities
>(decideMachine, runtimeSpec);

export default createPlaybookRuntime;
