// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by gears2fsm.md from ./decide.gears.md.
// FSM object artifact: it defines only the machine, actor contracts, and typed
// inputs; the linked runtime supplies the player and nested-playbook actors.
import { assign, fromPromise, setup } from 'xstate';
import { validatePlaybookCallResult } from '@sublang/playbook/xstate-runtime';
/**
 * One role-id array per parallel group, in first-item source order; each
 * inner array follows that group's item order (DECIDE-1, DECIDE-2).
 */
export const concurrentRoleSets = [
    ['coder', 'reviewer'],
];
const REVIEW_PLAYBOOK_ID = 'review';
const RESUMABLE_STATES = {
    askCoderProposal: { sourceItem: 'DECIDE-1', roleId: 'coder' },
    askReviewerProposal: { sourceItem: 'DECIDE-2', roleId: 'reviewer' },
    synthesizeCommit: { sourceItem: 'DECIDE-3', roleId: 'coder' },
};
// ---------------------------------------------------------------------------
// Prompts (each item's blockquote, verbatim) and local result contracts
// ---------------------------------------------------------------------------
const NEEDS_BOSS_REPLY_RESULT = "The acting agent's prose surfaces a clarifying question for Boss that the agent cannot answer alone. Output shall include `question: <verbatim question text from the acting agent's prose>`.";
/** DECIDE-1 blockquote; `<caller-topic>` is carried as `callerTopic`. */
const CODER_PROPOSAL_PROMPT = [
    'Assess whether the topic is better expressed as a few spec items under @specs/packages/ or requires one or more DRs under @specs/decisions/.',
    'Propose your design.',
    'Keep your proposal coherent, focused, and concise.',
    'Consult @specs/map.md for relevant context and @specs/meta.md for spec requirements, if needed.',
    'Do not change any files.',
    '',
    '> Original topic: <caller-topic>',
].join('\n');
/** DECIDE-2 blockquote; `<caller-topic>` is carried as `callerTopic`. */
const REVIEWER_PROPOSAL_PROMPT = [
    'Assess whether the topic is better expressed as a few spec items under @specs/packages/ or requires one or more DRs under @specs/decisions/.',
    'Propose your design.',
    'Keep your proposal coherent, focused, and concise.',
    'Consult @specs/map.md for relevant context and @specs/meta.md for spec requirements, if needed.',
    'Do not change any files.',
    '',
    '> Original topic: <caller-topic>',
].join('\n');
/**
 * DECIDE-3 blockquote. `<caller-topic>` is carried as `callerTopic` and
 * `<reviewer-proposal>` as `reviewerProposal`. `<coder-llm>` and
 * `<reviewer-llm>` are local-role prompt identities: the linker resolves them
 * through the invocation-scoped `promptIdentity(roleId)` lookup, so they stay
 * literal here and have no machine or actor-input field.
 */
const SYNTHESIZE_COMMIT_PROMPT = [
    "Synthesize your independent proposal with Reviewer's proposal below.",
    'Keep to the original topic below and follow what it asks.',
    'Keep the best, essential parts of either proposal and reject any point that is unsound, unnecessary, or outside the topic.',
    'Turn the resulting design into the necessary DRs and/or spec items.',
    'Follow @specs/meta.md and update @specs/map.md when needed.',
    'Do not change code or implement the design.',
    '',
    'Commit the result as one new commit, following @specs/packages/git.md.',
    'Make the commit message explain concisely what changed and why.',
    'Identify every new commit you make.',
    'Credit every AI that contributed to this commit: Coder <coder-llm> and Reviewer <reviewer-llm>, whose proposal it carries.',
    '',
    '> Original topic: <caller-topic>',
    "> Reviewer's independent proposal: <reviewer-proposal>",
].join('\n');
const CODER_PROPOSAL_RESULTS = {
    proposed: 'Coder affirmatively provided a complete design proposal; a progress report, status update, or promise of a later proposal supports no proposal outcome.',
    needsBossReply: NEEDS_BOSS_REPLY_RESULT,
};
const REVIEWER_PROPOSAL_RESULTS = {
    proposed: 'Reviewer affirmatively provided a complete design proposal; a progress report, status update, or promise of a later proposal supports no proposal outcome. Output shall include `reviewerProposal: <verbatim final text>`.',
    needsBossReply: NEEDS_BOSS_REPLY_RESULT,
};
const SYNTHESIZE_COMMIT_RESULTS = {
    committed: 'Coder committed the synthesized design as one new commit. Output shall include `coderOutput: <verbatim final text>` and `latestCommit: <commit identity>`.',
    needsBossReply: NEEDS_BOSS_REPLY_RESULT,
};
// ---------------------------------------------------------------------------
// State descriptions and public metadata
// ---------------------------------------------------------------------------
const STATE_DESCRIPTIONS = {
    ready: 'Waiting for the caller to give a topic to decide.',
    independentProposals: 'Coder and Reviewer independently propose designs for the topic in parallel.',
    coderProposalRegion: "Coder's independent proposal branch.",
    askCoderProposal: 'Coder is independently proposing a design for the topic.',
    awaitCoderProposalReply: "Waiting for Boss to answer Coder's question about its independent proposal.",
    coderProposalStaged: "Coder's independent proposal is complete and staged for the join.",
    reviewerProposalRegion: "Reviewer's independent proposal branch.",
    askReviewerProposal: 'Reviewer is independently proposing a design for the topic.',
    awaitReviewerProposalReply: "Waiting for Boss to answer Reviewer's question about its independent proposal.",
    reviewerProposalStaged: "Reviewer's independent proposal is complete and staged for the join.",
    synthesizeCommit: "Coder is synthesizing both proposals into DRs and/or spec items and committing the result.",
    awaitBossReply: "Waiting for Boss to answer the acting agent's question.",
    reviewCommit: 'The REVIEW playbook is reviewing the decide-owned commit.',
    failed: 'DECIDE failed and is waiting for Boss to recover it.',
    reportedReviewFailure: "DECIDE reported REVIEW's abort, failure, or unestablished result to its caller with the last decide-owned commit.",
    done: 'DECIDE completed: REVIEW established no unsettled findings for the decide-owned commit at the reported evaluated revision.',
};
function playbookMeta(stateId, role) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            ...(role === undefined ? {} : { role }),
        },
    };
}
function terminalMeta(stateId, terminal) {
    return {
        playbook: {
            stateId,
            description: STATE_DESCRIPTIONS[stateId],
            terminal,
        },
    };
}
// ---------------------------------------------------------------------------
// Structural narrowing helpers
// ---------------------------------------------------------------------------
function isObject(value) {
    return typeof value === 'object' && value !== null;
}
function isPlainRecord(value) {
    if (!isObject(value) || Array.isArray(value))
        return false;
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
}
function isNonEmptyString(value) {
    return typeof value === 'string' && value.trim().length > 0;
}
function isResumableStateId(value) {
    return (value === 'askCoderProposal' ||
        value === 'askReviewerProposal' ||
        value === 'synthesizeCommit');
}
/** The actor's `output`, narrowed structurally from an unknown done event. */
function actorOutput(event) {
    if (!isObject(event))
        return undefined;
    const output = event.output;
    return isPlainRecord(output) ? output : undefined;
}
function outputString(event, field) {
    const value = actorOutput(event)?.[field];
    return isNonEmptyString(value) ? value : undefined;
}
function outputGuardIs(event, guard) {
    return actorOutput(event)?.guard === guard;
}
/** The actor's `error`, narrowed structurally from an unknown error event. */
function actorError(event) {
    return isObject(event) ? event.error : undefined;
}
function errorRecord(value) {
    if (value instanceof Error) {
        return {
            name: typeof value.name === 'string' && value.name.length > 0
                ? value.name
                : 'Error',
            message: typeof value.message === 'string' ? value.message : '',
            ...(typeof value.stack === 'string' ? { stack: value.stack } : {}),
        };
    }
    return {
        name: 'Error',
        message: typeof value === 'string'
            ? value
            : 'The actor failed with a non-Error value.',
    };
}
function withoutKey(record, stateId) {
    const next = {};
    for (const key of Object.keys(record)) {
        if (!isResumableStateId(key) || key === stateId)
            continue;
        const value = record[key];
        if (value !== undefined)
            next[key] = value;
    }
    return next;
}
// ---------------------------------------------------------------------------
// Actor-output guards (narrow `event.output` to the declared contract)
// ---------------------------------------------------------------------------
function isCoderProposed(event) {
    return outputGuardIs(event, 'proposed');
}
function isReviewerProposed(event) {
    return (outputGuardIs(event, 'proposed') &&
        outputString(event, 'reviewerProposal') !== undefined);
}
function isCommitted(event) {
    return (outputGuardIs(event, 'committed') &&
        outputString(event, 'coderOutput') !== undefined &&
        outputString(event, 'latestCommit') !== undefined);
}
function isNeedsBossReply(event) {
    return (outputGuardIs(event, 'needsBossReply') &&
        outputString(event, 'question') !== undefined);
}
// ---------------------------------------------------------------------------
// Nested REVIEW result recognition
// ---------------------------------------------------------------------------
/**
 * Recognizes an authored rejected child result: a validated public result
 * whose status is `aborted` or `error`, or `ok` at the child's authored
 * failure terminal. Anything else is a control-plane error.
 */
export function authoredChildResult(error, expectedPlaybookId) {
    if (!(error instanceof Error))
        return undefined;
    try {
        const result = validatePlaybookCallResult(error.result, expectedPlaybookId);
        return result.status !== 'ok' || result.terminal?.kind === 'failure'
            ? result
            : undefined;
    }
    catch {
        return undefined;
    }
}
/**
 * DECIDE-4's acceptance predicate on the builtin REVIEW public interface:
 * the result gives the exact evaluated revision and affirmatively establishes
 * that no unsettled findings remain. The shared bridge correlates the call
 * with the supplied review scope.
 */
function reviewApprovalFrom(event) {
    const output = actorOutput(event);
    if (output === undefined)
        return undefined;
    if (output.noUnsettledFindings !== true ||
        !isNonEmptyString(output.evaluatedRevision)) {
        return undefined;
    }
    return {
        noUnsettledFindings: true,
        evaluatedRevision: output.evaluatedRevision,
    };
}
function authoredReviewOutcome(result) {
    if (result.status === 'aborted') {
        return {
            status: 'aborted',
            error: result.error === undefined
                ? { name: 'AbortError', message: 'REVIEW was aborted.' }
                : { name: result.error.name, message: result.error.message },
        };
    }
    if (result.status === 'error') {
        return {
            status: 'error',
            error: { name: result.error.name, message: result.error.message },
        };
    }
    // `ok` at REVIEW's own authored failure terminal: a REVIEW failure.
    const terminal = result.terminal;
    return {
        status: 'error',
        error: {
            name: 'ReviewFailure',
            message: terminal?.description !== undefined &&
                terminal.description.trim().length > 0
                ? terminal.description
                : `REVIEW ended at its failure terminal ${terminal?.stateId ?? 'state'}.`,
        },
    };
}
// ---------------------------------------------------------------------------
// Review input composition (DECIDE-4 quoted relays)
// ---------------------------------------------------------------------------
/**
 * One quoted relay: an empty value contributes no line, and a multi-line
 * value is quoted line by line.
 */
function quotedRelay(prefix, value, suffix = '') {
    if (value.length === 0)
        return [];
    const lines = value.split('\n');
    return lines.map((line, index) => {
        const head = index === 0 ? prefix : '> ';
        const tail = index === lines.length - 1 ? suffix : '';
        return `${head}${line}${tail}`;
    });
}
function reviewCallText(context) {
    return [
        ...quotedRelay('> Original intent: ', context.callerTopic),
        ...quotedRelay('> Review scope: the `decide`-owned commit ', context.decideCommit, ' and its resulting repository state.'),
        ...quotedRelay('> Coder output: ', context.coderOutput),
    ].join('\n');
}
// ---------------------------------------------------------------------------
// Player input mapping (pure reads of typed, entry-validated context)
// ---------------------------------------------------------------------------
function bossReplyFields(context, stateId) {
    const pendingBossQuestion = context.pendingBossQuestions[stateId];
    const bossReply = context.bossReplies[stateId];
    return {
        ...(pendingBossQuestion === undefined ? {} : { pendingBossQuestion }),
        ...(bossReply === undefined ? {} : { bossReply }),
    };
}
// ---------------------------------------------------------------------------
// Transition helpers
// ---------------------------------------------------------------------------
/**
 * Accepted-outcome marker (artifact schema 3). `target` names the state the
 * public snapshot shows after the transition's macrostep.
 */
function acceptedOutcome(source, target, outcome) {
    return {
        type: 'playbook.acceptedOutcome',
        params: { source, target, acceptedOutcome: outcome },
    };
}
/** Root BOSS_INTERRUPT arms, one per jumpable state. */
function bossInterrupts(ids) {
    return ids.map((targetId) => ({
        guard: { type: 'interruptTargets', params: { targetId } },
        target: `#${targetId}`,
        reenter: true,
        actions: 'restartFromInterrupt',
    }));
}
/**
 * Keyed BOSS_REPLY arms of the wait that resumes the given working leaves.
 * A branch-local wait leaves a reply naming no pending question unhandled, so
 * an unknown id never moves that branch while its sibling may still be
 * working; the root wait routes such a reply to `failed`.
 */
function resumableStates(ids) {
    return ids.flatMap((stateId) => [
        {
            guard: { type: 'bossReplyIsEmpty', params: { stateId } },
            target: '#failed',
            actions: 'rememberEmptyBossReply',
        },
        {
            guard: { type: 'bossReplyResumes', params: { stateId } },
            target: `#${stateId}`,
            reenter: true,
            actions: { type: 'rememberBossReply', params: { stateId } },
        },
    ]);
}
/** Root-wait BOSS_REPLY arms: an unknown id fails before any resume arm. */
function rootResumableStates(ids) {
    return [
        {
            guard: 'bossReplyNamesNoPendingQuestion',
            target: '#failed',
            actions: 'rememberUnknownBossReply',
        },
        ...resumableStates(ids),
    ];
}
const INITIAL_CONTEXT = {
    callerTopic: '',
    stagedCoderProposed: false,
    stagedReviewerProposal: '',
    coderProposed: false,
    reviewerProposal: '',
    coderOutput: '',
    decideCommit: '',
    evaluatedRevision: '',
    reviewStatus: null,
    reviewError: null,
    lastError: null,
    pendingBossQuestions: {},
    bossReplies: {},
};
/** A fresh run for a topic: clears every prior result, error, and question. */
function freshRun(callerTopic) {
    return { ...INITIAL_CONTEXT, callerTopic };
}
/** Context reset shared by every exit into `failed`. */
const FAILURE_RESET = {
    pendingBossQuestions: {},
    bossReplies: {},
    stagedCoderProposed: false,
    stagedReviewerProposal: '',
};
/**
 * A synthesis restart keeps the topic and the promoted proposals, and clears
 * the prior commit, review evidence, error, and every pending question.
 */
const SYNTHESIS_RESTART = {
    coderOutput: '',
    decideCommit: '',
    evaluatedRevision: '',
    reviewStatus: null,
    reviewError: null,
    lastError: null,
    pendingBossQuestions: {},
    bossReplies: {},
};
// ---------------------------------------------------------------------------
// Machine
// ---------------------------------------------------------------------------
const machineSetup = setup({
    types: {},
    actors: {
        player: fromPromise(async () => {
            throw new Error('player actor must be provided by the runner');
        }),
        playbook: fromPromise(async () => {
            throw new Error('playbook actor must be provided by the runner');
        }),
    },
    guards: {
        validStartTopic: ({ event }) => event.type === 'START_DECIDE' && isNonEmptyString(event.callerTopic),
        // Each arm guards its target id and every typed precondition for
        // entering that target safely.
        interruptTargets: ({ context, event }, params) => {
            if (event.type !== 'BOSS_INTERRUPT')
                return false;
            if (event.targetId !== params.targetId)
                return false;
            if (event.targetId === 'independentProposals') {
                return isNonEmptyString(event.callerTopic);
            }
            return (isNonEmptyString(context.callerTopic) &&
                isNonEmptyString(context.reviewerProposal));
        },
        // A branch completing after its sibling has staged its proposal also
        // completes the join, so its accepted outcome lands on `synthesizeCommit`.
        coderProposedJoining: ({ context, event }) => isCoderProposed(event) &&
            isNonEmptyString(context.stagedReviewerProposal) &&
            isNonEmptyString(context.callerTopic),
        coderProposed: ({ event }) => isCoderProposed(event),
        reviewerProposedJoining: ({ context, event }) => isReviewerProposed(event) &&
            context.stagedCoderProposed &&
            isNonEmptyString(context.callerTopic),
        reviewerProposed: ({ event }) => isReviewerProposed(event),
        committed: ({ event }) => isCommitted(event),
        needsBossReply: ({ event }) => isNeedsBossReply(event),
        reviewApproved: ({ context, event }) => isNonEmptyString(context.decideCommit) &&
            reviewApprovalFrom(event) !== undefined,
        authoredReviewFailure: ({ context, event }) => isNonEmptyString(context.decideCommit) &&
            authoredChildResult(actorError(event), REVIEW_PLAYBOOK_ID) !== undefined,
        bossReplyNamesNoPendingQuestion: ({ context, event }) => event.type === 'BOSS_REPLY' &&
            (!isResumableStateId(event.questionId) ||
                context.pendingBossQuestions[event.questionId] === undefined),
        bossReplyIsEmpty: ({ context, event }, params) => event.type === 'BOSS_REPLY' &&
            event.questionId === params.stateId &&
            context.pendingBossQuestions[params.stateId] !== undefined &&
            !isNonEmptyString(event.answer),
        bossReplyResumes: ({ context, event }, params) => event.type === 'BOSS_REPLY' &&
            event.questionId === params.stateId &&
            context.pendingBossQuestions[params.stateId] !== undefined &&
            isNonEmptyString(event.answer) &&
            isNonEmptyString(context.callerTopic),
    },
    actions: {
        'playbook.acceptedOutcome': (_args, _params) => undefined,
        startDecide: assign(({ event }) => event.type === 'START_DECIDE' ? freshRun(event.callerTopic) : {}),
        // A new topic restarts the whole proposal pair: it clears staged results,
        // promoted proposals, commit and review evidence, errors, and every
        // pending Boss question and reply.
        restartFromInterrupt: assign(({ event }) => {
            if (event.type !== 'BOSS_INTERRUPT')
                return {};
            return event.targetId === 'independentProposals'
                ? freshRun(event.callerTopic)
                : SYNTHESIS_RESTART;
        }),
        stageCoderProposal: assign(({ context }) => ({
            stagedCoderProposed: true,
            pendingBossQuestions: withoutKey(context.pendingBossQuestions, 'askCoderProposal'),
            bossReplies: withoutKey(context.bossReplies, 'askCoderProposal'),
        })),
        stageReviewerProposal: assign(({ context, event }) => ({
            stagedReviewerProposal: outputString(event, 'reviewerProposal') ?? '',
            pendingBossQuestions: withoutKey(context.pendingBossQuestions, 'askReviewerProposal'),
            bossReplies: withoutKey(context.bossReplies, 'askReviewerProposal'),
        })),
        promoteProposals: assign(({ context }) => ({
            coderProposed: context.stagedCoderProposed,
            reviewerProposal: context.stagedReviewerProposal,
            stagedCoderProposed: false,
            stagedReviewerProposal: '',
            pendingBossQuestions: {},
            bossReplies: {},
        })),
        rememberCommit: assign(({ context, event }) => ({
            coderOutput: outputString(event, 'coderOutput') ?? '',
            decideCommit: outputString(event, 'latestCommit') ?? '',
            pendingBossQuestions: withoutKey(context.pendingBossQuestions, 'synthesizeCommit'),
            bossReplies: withoutKey(context.bossReplies, 'synthesizeCommit'),
        })),
        setPendingBossQuestion: assign(({ context, event }, params) => {
            const question = outputString(event, 'question');
            if (question === undefined)
                return {};
            const { sourceItem, roleId } = RESUMABLE_STATES[params.stateId];
            return {
                pendingBossQuestions: {
                    ...context.pendingBossQuestions,
                    [params.stateId]: {
                        questionId: params.stateId,
                        resumeStateId: params.stateId,
                        sourceItem,
                        asker: { kind: 'role', roleId },
                        question,
                    },
                },
                bossReplies: withoutKey(context.bossReplies, params.stateId),
            };
        }),
        rememberBossReply: assign(({ context, event }, params) => event.type === 'BOSS_REPLY'
            ? {
                bossReplies: {
                    ...context.bossReplies,
                    [params.stateId]: event.answer,
                },
            }
            : {}),
        rememberEmptyBossReply: assign({
            lastError: {
                name: 'BossReplyError',
                message: 'BOSS_REPLY received an empty answer.',
            },
            ...FAILURE_RESET,
        }),
        rememberUnknownBossReply: assign({
            lastError: {
                name: 'BossReplyError',
                message: 'BOSS_REPLY names no pending question.',
            },
            ...FAILURE_RESET,
        }),
        rememberMalformedPlayerOutput: assign((_args, params) => ({
            lastError: {
                name: 'PlayerOutputError',
                message: `Player result for ${params.sourceItem} did not match a declared outcome.`,
            },
            ...FAILURE_RESET,
        })),
        rememberActorError: assign(({ event }) => ({
            lastError: errorRecord(actorError(event)),
            ...FAILURE_RESET,
        })),
        rememberReviewApproval: assign(({ event }) => ({
            evaluatedRevision: reviewApprovalFrom(event)?.evaluatedRevision ?? '',
            reviewStatus: null,
            reviewError: null,
        })),
        rememberAuthoredReviewFailure: assign(({ event }) => {
            const result = authoredChildResult(actorError(event), REVIEW_PLAYBOOK_ID);
            if (result === undefined)
                return {};
            const outcome = authoredReviewOutcome(result);
            return {
                evaluatedRevision: '',
                reviewStatus: outcome.status,
                reviewError: outcome.error,
            };
        }),
        rememberUnestablishedReview: assign({
            evaluatedRevision: '',
            reviewStatus: 'error',
            reviewError: {
                name: 'ReviewContractError',
                message: 'REVIEW returned a result that does not establish the evaluated repository revision with no unsettled findings.',
            },
        }),
    },
});
export const decideMachine = machineSetup.createMachine({
    id: 'decide',
    description: 'DECIDE: independent Coder and Reviewer proposals, a synthesized decide-owned commit, and a nested REVIEW.',
    initial: 'ready',
    context: () => INITIAL_CONTEXT,
    output: ({ context }) => {
        const commit = context.decideCommit;
        if (!isNonEmptyString(commit)) {
            throw new Error('DECIDE reached a final state without its decide-owned commit');
        }
        if (context.reviewStatus !== null) {
            return {
                lastDecideCommit: commit,
                noUnsettledFindings: false,
                reviewStatus: context.reviewStatus,
                ...(context.reviewError === null ? {} : { error: context.reviewError }),
            };
        }
        const evaluatedRevision = context.evaluatedRevision;
        if (!isNonEmptyString(evaluatedRevision)) {
            throw new Error('DECIDE completed without an evaluated repository revision');
        }
        return {
            decideCommit: commit,
            evaluatedRevision,
            noUnsettledFindings: true,
        };
    },
    on: {
        BOSS_INTERRUPT: bossInterrupts(['independentProposals', 'synthesizeCommit']),
    },
    states: {
        ready: {
            id: 'ready',
            description: STATE_DESCRIPTIONS.ready,
            meta: playbookMeta('ready'),
            tags: ['playbook.parked'],
            on: {
                START_DECIDE: {
                    guard: 'validStartTopic',
                    target: 'independentProposals',
                    actions: 'startDecide',
                },
            },
        },
        independentProposals: {
            id: 'independentProposals',
            description: STATE_DESCRIPTIONS.independentProposals,
            meta: playbookMeta('independentProposals'),
            type: 'parallel',
            states: {
                coderProposalRegion: {
                    id: 'coderProposalRegion',
                    description: STATE_DESCRIPTIONS.coderProposalRegion,
                    meta: playbookMeta('coderProposalRegion'),
                    initial: 'askCoderProposal',
                    states: {
                        askCoderProposal: {
                            id: 'askCoderProposal',
                            description: STATE_DESCRIPTIONS.askCoderProposal,
                            meta: playbookMeta('askCoderProposal', 'coder'),
                            tags: ['playbook.busy'],
                            invoke: {
                                src: 'player',
                                input: ({ context }) => ({
                                    stateId: 'askCoderProposal',
                                    role: 'coder',
                                    sourceItem: 'DECIDE-1',
                                    prompt: CODER_PROPOSAL_PROMPT,
                                    result: CODER_PROPOSAL_RESULTS,
                                    callerTopic: context.callerTopic,
                                    ...bossReplyFields(context, 'askCoderProposal'),
                                }),
                                onDone: [
                                    {
                                        guard: 'coderProposedJoining',
                                        target: 'coderProposalStaged',
                                        actions: [
                                            acceptedOutcome('askCoderProposal', 'synthesizeCommit', 'proposed'),
                                            'stageCoderProposal',
                                        ],
                                    },
                                    {
                                        guard: 'coderProposed',
                                        target: 'coderProposalStaged',
                                        actions: [
                                            acceptedOutcome('askCoderProposal', 'coderProposalStaged', 'proposed'),
                                            'stageCoderProposal',
                                        ],
                                    },
                                    {
                                        guard: 'needsBossReply',
                                        target: 'awaitCoderProposalReply',
                                        actions: [
                                            acceptedOutcome('askCoderProposal', 'awaitCoderProposalReply', 'needsBossReply'),
                                            {
                                                type: 'setPendingBossQuestion',
                                                params: { stateId: 'askCoderProposal' },
                                            },
                                        ],
                                    },
                                    {
                                        target: '#failed',
                                        actions: {
                                            type: 'rememberMalformedPlayerOutput',
                                            params: { sourceItem: 'DECIDE-1' },
                                        },
                                    },
                                ],
                                onError: {
                                    target: '#failed',
                                    actions: 'rememberActorError',
                                },
                            },
                        },
                        awaitCoderProposalReply: {
                            id: 'awaitCoderProposalReply',
                            description: STATE_DESCRIPTIONS.awaitCoderProposalReply,
                            meta: playbookMeta('awaitCoderProposalReply'),
                            tags: ['playbook.parked'],
                            on: {
                                BOSS_REPLY: resumableStates(['askCoderProposal']),
                            },
                        },
                        coderProposalStaged: {
                            id: 'coderProposalStaged',
                            description: STATE_DESCRIPTIONS.coderProposalStaged,
                            meta: playbookMeta('coderProposalStaged'),
                            type: 'final',
                        },
                    },
                },
                reviewerProposalRegion: {
                    id: 'reviewerProposalRegion',
                    description: STATE_DESCRIPTIONS.reviewerProposalRegion,
                    meta: playbookMeta('reviewerProposalRegion'),
                    initial: 'askReviewerProposal',
                    states: {
                        askReviewerProposal: {
                            id: 'askReviewerProposal',
                            description: STATE_DESCRIPTIONS.askReviewerProposal,
                            meta: playbookMeta('askReviewerProposal', 'reviewer'),
                            tags: ['playbook.busy'],
                            invoke: {
                                src: 'player',
                                input: ({ context }) => ({
                                    stateId: 'askReviewerProposal',
                                    role: 'reviewer',
                                    sourceItem: 'DECIDE-2',
                                    prompt: REVIEWER_PROPOSAL_PROMPT,
                                    result: REVIEWER_PROPOSAL_RESULTS,
                                    callerTopic: context.callerTopic,
                                    ...bossReplyFields(context, 'askReviewerProposal'),
                                }),
                                onDone: [
                                    {
                                        guard: 'reviewerProposedJoining',
                                        target: 'reviewerProposalStaged',
                                        actions: [
                                            acceptedOutcome('askReviewerProposal', 'synthesizeCommit', 'proposed'),
                                            'stageReviewerProposal',
                                        ],
                                    },
                                    {
                                        guard: 'reviewerProposed',
                                        target: 'reviewerProposalStaged',
                                        actions: [
                                            acceptedOutcome('askReviewerProposal', 'reviewerProposalStaged', 'proposed'),
                                            'stageReviewerProposal',
                                        ],
                                    },
                                    {
                                        guard: 'needsBossReply',
                                        target: 'awaitReviewerProposalReply',
                                        actions: [
                                            acceptedOutcome('askReviewerProposal', 'awaitReviewerProposalReply', 'needsBossReply'),
                                            {
                                                type: 'setPendingBossQuestion',
                                                params: { stateId: 'askReviewerProposal' },
                                            },
                                        ],
                                    },
                                    {
                                        target: '#failed',
                                        actions: {
                                            type: 'rememberMalformedPlayerOutput',
                                            params: { sourceItem: 'DECIDE-2' },
                                        },
                                    },
                                ],
                                onError: {
                                    target: '#failed',
                                    actions: 'rememberActorError',
                                },
                            },
                        },
                        awaitReviewerProposalReply: {
                            id: 'awaitReviewerProposalReply',
                            description: STATE_DESCRIPTIONS.awaitReviewerProposalReply,
                            meta: playbookMeta('awaitReviewerProposalReply'),
                            tags: ['playbook.parked'],
                            on: {
                                BOSS_REPLY: resumableStates(['askReviewerProposal']),
                            },
                        },
                        reviewerProposalStaged: {
                            id: 'reviewerProposalStaged',
                            description: STATE_DESCRIPTIONS.reviewerProposalStaged,
                            meta: playbookMeta('reviewerProposalStaged'),
                            type: 'final',
                        },
                    },
                },
            },
            // The join: taken only after both regions reach final; it promotes both
            // staged proposals atomically before DECIDE-3 begins.
            onDone: {
                target: 'synthesizeCommit',
                actions: 'promoteProposals',
            },
        },
        synthesizeCommit: {
            id: 'synthesizeCommit',
            description: STATE_DESCRIPTIONS.synthesizeCommit,
            meta: playbookMeta('synthesizeCommit', 'coder'),
            tags: ['playbook.busy'],
            invoke: {
                src: 'player',
                input: ({ context }) => ({
                    stateId: 'synthesizeCommit',
                    role: 'coder',
                    sourceItem: 'DECIDE-3',
                    prompt: SYNTHESIZE_COMMIT_PROMPT,
                    result: SYNTHESIZE_COMMIT_RESULTS,
                    callerTopic: context.callerTopic,
                    reviewerProposal: context.reviewerProposal,
                    ...bossReplyFields(context, 'synthesizeCommit'),
                }),
                onDone: [
                    {
                        guard: 'committed',
                        target: 'reviewCommit',
                        actions: [
                            acceptedOutcome('synthesizeCommit', 'reviewCommit', 'committed'),
                            'rememberCommit',
                        ],
                    },
                    {
                        guard: 'needsBossReply',
                        target: 'awaitBossReply',
                        actions: [
                            acceptedOutcome('synthesizeCommit', 'awaitBossReply', 'needsBossReply'),
                            {
                                type: 'setPendingBossQuestion',
                                params: { stateId: 'synthesizeCommit' },
                            },
                        ],
                    },
                    {
                        target: 'failed',
                        actions: {
                            type: 'rememberMalformedPlayerOutput',
                            params: { sourceItem: 'DECIDE-3' },
                        },
                    },
                ],
                onError: { target: 'failed', actions: 'rememberActorError' },
            },
        },
        awaitBossReply: {
            id: 'awaitBossReply',
            description: STATE_DESCRIPTIONS.awaitBossReply,
            meta: playbookMeta('awaitBossReply'),
            tags: ['playbook.parked'],
            on: {
                BOSS_REPLY: rootResumableStates(['synthesizeCommit']),
                START_DECIDE: {
                    guard: 'validStartTopic',
                    target: 'independentProposals',
                    actions: 'startDecide',
                },
            },
        },
        reviewCommit: {
            id: 'reviewCommit',
            description: STATE_DESCRIPTIONS.reviewCommit,
            meta: playbookMeta('reviewCommit'),
            tags: ['playbook.suspended'],
            invoke: {
                src: 'playbook',
                input: ({ context }) => ({
                    stateId: 'reviewCommit',
                    sourceItem: 'DECIDE-4',
                    playbookId: REVIEW_PLAYBOOK_ID,
                    text: reviewCallText(context),
                }),
                onDone: [
                    {
                        guard: 'reviewApproved',
                        target: 'done',
                        actions: 'rememberReviewApproval',
                    },
                    {
                        target: 'reportedReviewFailure',
                        actions: 'rememberUnestablishedReview',
                    },
                ],
                onError: [
                    {
                        guard: 'authoredReviewFailure',
                        target: 'reportedReviewFailure',
                        actions: 'rememberAuthoredReviewFailure',
                    },
                    { target: 'failed', actions: 'rememberActorError' },
                ],
            },
        },
        failed: {
            id: 'failed',
            description: STATE_DESCRIPTIONS.failed,
            meta: playbookMeta('failed'),
            tags: ['playbook.parked'],
            on: {
                START_DECIDE: {
                    guard: 'validStartTopic',
                    target: 'independentProposals',
                    actions: 'startDecide',
                },
            },
        },
        reportedReviewFailure: {
            id: 'reportedReviewFailure',
            description: STATE_DESCRIPTIONS.reportedReviewFailure,
            meta: terminalMeta('reportedReviewFailure', 'failure'),
            type: 'final',
        },
        done: {
            id: 'done',
            description: STATE_DESCRIPTIONS.done,
            meta: terminalMeta('done', 'success'),
            type: 'final',
        },
    },
});
export default decideMachine;
