// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by gears2fsm.md from ./review.gears.md.

import { assign, fromPromise, setup } from 'xstate';

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

/** Stable ids of the working leaves; each is also a Boss-reply resume target. */
export type ReviewStateId =
  | 'reviewFirstRound'
  | 'fixFindings'
  | 'reviewAfterCommit'
  | 'reviewAfterRejection';

export type ReviewSourceItem = 'REVIEW-1' | 'REVIEW-2' | 'REVIEW-3' | 'REVIEW-4';

export type ReviewRoleId = 'coder' | 'reviewer';

export type PendingBossQuestion = {
  readonly questionId: ReviewStateId;
  readonly resumeStateId: ReviewStateId;
  readonly sourceItem: ReviewSourceItem;
  readonly asker: { readonly kind: 'role'; readonly roleId: ReviewRoleId };
  readonly question: string;
};

type PlayerInputBase<
  StateId extends ReviewStateId,
  RoleId extends ReviewRoleId,
  SourceItem extends ReviewSourceItem,
> = {
  readonly stateId: StateId;
  readonly role: RoleId;
  readonly sourceItem: SourceItem;
  readonly prompt: string;
  readonly result: Readonly<Record<string, string>>;
  readonly pendingBossQuestion?: PendingBossQuestion;
  readonly bossReply?: string;
};

/** REVIEW-1: first review round; relays `<caller-input>`. */
export type ReviewFirstRoundInput = PlayerInputBase<
  'reviewFirstRound',
  'reviewer',
  'REVIEW-1'
> & {
  readonly callerInput: string;
};

/** REVIEW-2: Coder disposition round; relays `<caller-input>` and `<reviewer-output>`. */
export type FixFindingsInput = PlayerInputBase<
  'fixFindings',
  'coder',
  'REVIEW-2'
> & {
  readonly callerInput: string;
  readonly reviewerOutput: string;
};

/** REVIEW-3: round after a review-fix commit; relays `<caller-input>`, `<latest-commit>`, `<coder-output>`. */
export type ReviewAfterCommitInput = PlayerInputBase<
  'reviewAfterCommit',
  'reviewer',
  'REVIEW-3'
> & {
  readonly callerInput: string;
  readonly latestCommit: string;
  readonly coderOutput: string;
};

/** REVIEW-4: round after Coder rejected every finding; relays `<caller-input>` and `<coder-output>`. */
export type ReviewAfterRejectionInput = PlayerInputBase<
  'reviewAfterRejection',
  'reviewer',
  'REVIEW-4'
> & {
  readonly callerInput: string;
  readonly coderOutput: string;
};

export type PlayerInput =
  | ReviewFirstRoundInput
  | FixFindingsInput
  | ReviewAfterCommitInput
  | ReviewAfterRejectionInput;

export type ReviewerOutput =
  | { readonly guard: 'findings'; readonly reviewerOutput: string }
  | {
      readonly guard: 'clean';
      /** Receipt-owned repository revision the clean round evaluated. */
      readonly evaluatedRevision: string;
    }
  | { readonly guard: 'needsBossReply'; readonly question: string };

export type CoderOutput =
  | {
      readonly guard: 'committed';
      /** Receipt-owned identity of the new review-fix commit. */
      readonly latestCommit: string;
      readonly coderOutput: string;
    }
  | { readonly guard: 'rejectedAll'; readonly coderOutput: string }
  | { readonly guard: 'needsBossReply'; readonly question: string };

export type PlayerOutput = ReviewerOutput | CoderOutput;

/** Public REVIEW output interface (workflow-contracts.json `review`). */
export type ReviewPlaybookOutput = {
  readonly noUnsettledFindings: true;
  /** Exact receipt-observed repository revision evaluated by the final clean review round. */
  readonly evaluatedRevision: string;
};

export type ReviewInput = Readonly<Record<string, never>>;

export type NormalizedError = {
  readonly name: string;
  readonly message: string;
  readonly stack?: string;
};

export type CoderOutcome = 'committed' | 'rejectedAll';

export type ReviewContext = {
  readonly callerInput?: string;
  readonly reviewerOutput?: string;
  readonly latestCommit?: string;
  readonly coderOutput?: string;
  readonly coderOutcome?: CoderOutcome;
  readonly evaluatedRevision?: string;
  readonly lastError?: NormalizedError;
  readonly pendingBossQuestion?: PendingBossQuestion;
  readonly bossReply?: string;
};

export type ReviewEvent =
  | { readonly type: 'START_REVIEW'; readonly callerInput: string }
  | { readonly type: 'BOSS_INTERRUPT'; readonly targetId: ReviewStateId }
  | {
      readonly type: 'BOSS_REPLY';
      readonly answer: string;
      readonly questionId?: ReviewStateId;
    };

const SHARED_ROUND_INSTRUCTION = [
  'Understand the full picture and think systematically about the underlying design.',
  'Continue to identify issues or improvements, if any, without duplication.',
  'Number the findings consistently across rounds.',
  'Flag only what materially affects correctness, behavior, or spec quality — not style, equally valid alternatives, or theoretical threats.',
  'For specs, flag stale, missing, over-specified, or under-specified ones, if any.',
  'Avoid unnecessary complexity in code or tests, but flag any fundamental design flaw when leaving it would cost more in later patches than fixing it now.',
  '',
  'If an issue represents a class of defect, find every instance within the review scope worth fixing rather than surfacing one or two per round, which drags out the review.',
  'For any rebuttal, accept or challenge it.',
  'Treat as settled, and do not raise again, any finding in this review rejected twice with reasoning.',
  '',
  'Do not re-run tests or builds whose inputs have not changed since any previous reported run.',
  'Do not edit files or commit; report findings only.',
  '',
  'Consult @specs/map.md for context if needed; verify it remains accurate.',
  'Consult @specs/meta.md for spec requirements if needed; verify affected specs follow it.',
] as const;

const REVIEW_FIRST_ROUND_PROMPT = [
  'A new review begins for the review scope.',
  'Keep to the original intent and follow what it asks.',
  'When the scope names commits, read each commit message for its context and rationale; otherwise use repository history and commit messages wherever they help establish that context.',
  '',
  ...SHARED_ROUND_INSTRUCTION,
  '',
  '> Original request: <caller-input>',
].join('\n');

const FIX_FINDINGS_PROMPT = [
  'For each review item, accept or reject it.',
  'Before deciding, understand the full picture and think systematically about the underlying design.',
  'Keep to the original intent and follow what it asks.',
  'Reject anything that is not essential or is not worth fixing now.',
  'If you accept an item, fix its root cause, including any fundamental design flaw — do not patch around it; if it represents a class of defect, find every instance within the review scope worth fixing rather than addressing one or two per round, which drags out the review.',
  'If you reject an item, give the reasoning and cite code or test output that supports it.',
  'Do not re-run tests or builds whose inputs have not changed since any previous reported run.',
  '',
  'If you accept any item, make minimal changes and add one new review-fix commit; never rewrite any existing commit.',
  'Follow @specs/packages/git.md.',
  'Make the commit message explain concisely what changed and why, including relevant verification.',
  'Identify every new commit you make.',
  'Credit every AI that contributed to this commit: Coder <coder-llm> and Reviewer <reviewer-llm>, whose findings it answers.',
  '',
  'If you reject every item, change nothing and make no commit.',
  'Report every disposition, all relevant run results, and every rebuttal.',
  '',
  '> Original request: <caller-input>',
  '> Reviewer findings: <reviewer-output>',
].join('\n');

const REVIEW_AFTER_COMMIT_PROMPT = [
  'A new review round begins for the review scope in the cumulative committed state, with particular attention to the latest review-fix commit.',
  'Keep to the original intent and follow what it asks.',
  "Read the latest review-fix commit's message and see Coder's feedback below.",
  '',
  ...SHARED_ROUND_INSTRUCTION,
  '',
  '> Original request: <caller-input>',
  '> Latest commit: <latest-commit>',
  '> Coder output: <coder-output>',
].join('\n');

const REVIEW_AFTER_REJECTION_PROMPT = [
  'No new commit was made because Coder rejected every finding.',
  "See Coder's feedback below.",
  '',
  ...SHARED_ROUND_INSTRUCTION,
  '',
  '> Original request: <caller-input>',
  '> Coder output: <coder-output>',
].join('\n');

const NEEDS_BOSS_REPLY_RESULT =
  "The acting agent's prose surfaces a clarifying question for Boss that the agent cannot answer alone. Output shall include `question: <verbatim question text from the acting agent's prose>`.";

const REVIEW_FIRST_ROUND_RESULTS = {
  findings:
    "Reviewer raised one or more findings that remain unsettled. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. Output shall include `reviewerOutput: <verbatim final text>`.",
  clean:
    "Reviewer affirmatively reported that the requested review is complete and no unsettled findings remain. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. The review workflow then returns the exact repository revision at which the review scope was evaluated, taken from repository authority rather than from either player's prose, and the fact that no unsettled findings remain within that scope. Output shall include `evaluatedRevision: <repository revision>`.",
  needsBossReply: NEEDS_BOSS_REPLY_RESULT,
} as const;

const FIX_FINDINGS_RESULTS = {
  committed:
    "Coder accepted one or more findings and made one new review-fix commit, whose identity is taken from the repository-effect receipt rather than from Coder's prose; the outcome does not depend on finding numbers or any fixed presentation format of Coder's reply. Output shall include `latestCommit: <commit identity>` and `coderOutput: <verbatim final text>`.",
  rejectedAll:
    "Coder rejected every finding and made no commit; the outcome does not depend on finding numbers or any fixed presentation format of Coder's reply. Output shall include `coderOutput: <verbatim final text>`.",
  needsBossReply: NEEDS_BOSS_REPLY_RESULT,
} as const;

const REVIEW_AFTER_COMMIT_RESULTS = {
  findings:
    "Reviewer raised or kept one or more findings that remain unsettled. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. Output shall include `reviewerOutput: <verbatim final text>`.",
  clean:
    "Reviewer affirmatively reported that the requested review is complete and no unsettled findings remain. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. The review workflow then returns the exact repository revision at which the review scope was evaluated, taken from repository authority rather than from either player's prose, and the fact that no unsettled findings remain within that scope. Output shall include `evaluatedRevision: <repository revision>`.",
  needsBossReply: NEEDS_BOSS_REPLY_RESULT,
} as const;

const REVIEW_AFTER_REJECTION_RESULTS = {
  findings:
    "Reviewer kept or raised one or more findings that remain unsettled. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. Output shall include `reviewerOutput: <verbatim final text>`.",
  clean:
    "Reviewer affirmatively reported that the requested review is complete and no unsettled findings remain. The outcome depends on the substance of Reviewer's reply, not on finding numbers or any fixed presentation format; a progress report, status update, or promise of a later result does not support this outcome. The review workflow then returns the exact repository revision at which the review scope was evaluated, taken from repository authority rather than from either player's prose, and the fact that no unsettled findings remain within that scope. Output shall include `evaluatedRevision: <repository revision>`.",
  needsBossReply: NEEDS_BOSS_REPLY_RESULT,
} as const;

const STATE_DESCRIPTIONS = {
  ready: 'Waiting for a caller input to start a review.',
  reviewFirstRound:
    "Reviewer is running the first review round over the caller's review scope.",
  fixFindings:
    "Coder is accepting or rejecting Reviewer's unsettled findings and committing any fixes.",
  reviewAfterCommit:
    'Reviewer is reviewing the cumulative committed state after the latest review-fix commit.',
  reviewAfterRejection:
    'Reviewer is reviewing the same committed state after Coder rejected every finding.',
  awaitBossReply: "Waiting for Boss to answer the acting agent's question.",
  failed: 'The review workflow failed and is waiting for Boss to recover it.',
  done: 'The review completed with no unsettled findings; it returns the exact repository revision at which the review scope was evaluated.',
} as const;

type DescribedStateId = keyof typeof STATE_DESCRIPTIONS;

export const concurrentRoleSets: readonly (readonly ReviewRoleId[])[] = [];

const RESUMABLE_STATE_IDS = [
  'reviewFirstRound',
  'fixFindings',
  'reviewAfterCommit',
  'reviewAfterRejection',
] as const satisfies readonly ReviewStateId[];

function playbookMeta(stateId: DescribedStateId, role?: ReviewRoleId) {
  return {
    playbook: {
      stateId,
      description: STATE_DESCRIPTIONS[stateId],
      ...(role === undefined ? {} : { role }),
    },
  };
}

function terminalMeta(
  stateId: DescribedStateId,
  terminal: 'success' | 'failure',
) {
  return {
    playbook: {
      stateId,
      description: STATE_DESCRIPTIONS[stateId],
      terminal,
    },
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function playerOutput(event: unknown): Record<string, unknown> | undefined {
  if (!isRecord(event)) return undefined;
  return isRecord(event.output) ? event.output : undefined;
}

function outputGuard(event: unknown, guard: PlayerOutput['guard']): boolean {
  return playerOutput(event)?.guard === guard;
}

function outputString(event: unknown, field: string): string | undefined {
  const value = playerOutput(event)?.[field];
  return isNonEmptyString(value) ? value : undefined;
}

function actorError(event: unknown): unknown {
  return isRecord(event) ? event.error : undefined;
}

function normalizeError(value: unknown): NormalizedError {
  if (value instanceof Error) {
    return {
      name: typeof value.name === 'string' && value.name ? value.name : 'Error',
      message: typeof value.message === 'string' ? value.message : '',
      ...(typeof value.stack === 'string' ? { stack: value.stack } : {}),
    };
  }
  return {
    name: 'Error',
    message:
      typeof value === 'string' ? value : 'The actor failed with a non-Error value.',
  };
}

// Guards on actor output narrow `event.output` structurally to the declared
// player contract before reading any field.

function isFindings({ event }: { event: unknown }): boolean {
  return (
    outputGuard(event, 'findings') &&
    outputString(event, 'reviewerOutput') !== undefined
  );
}

function isClean({ event }: { event: unknown }): boolean {
  return (
    outputGuard(event, 'clean') &&
    outputString(event, 'evaluatedRevision') !== undefined
  );
}

function isCommitted({ event }: { event: unknown }): boolean {
  return (
    outputGuard(event, 'committed') &&
    outputString(event, 'latestCommit') !== undefined &&
    outputString(event, 'coderOutput') !== undefined
  );
}

function isRejectedAll({ event }: { event: unknown }): boolean {
  return (
    outputGuard(event, 'rejectedAll') &&
    outputString(event, 'coderOutput') !== undefined
  );
}

function needsBossReply({ event }: { event: unknown }): boolean {
  return (
    outputGuard(event, 'needsBossReply') &&
    outputString(event, 'question') !== undefined
  );
}

/** Typed context preconditions for entering each working leaf safely. */
function canEnter(context: ReviewContext, stateId: ReviewStateId): boolean {
  if (!isNonEmptyString(context.callerInput)) return false;
  switch (stateId) {
    case 'reviewFirstRound':
      return true;
    case 'fixFindings':
      return isNonEmptyString(context.reviewerOutput);
    case 'reviewAfterCommit':
      return (
        context.coderOutcome === 'committed' &&
        isNonEmptyString(context.latestCommit) &&
        isNonEmptyString(context.coderOutput)
      );
    case 'reviewAfterRejection':
      return (
        context.coderOutcome === 'rejectedAll' &&
        isNonEmptyString(context.coderOutput)
      );
  }
}

function resolvedQuestionId(
  context: ReviewContext,
  event: ReviewEvent,
): ReviewStateId | undefined {
  if (event.type !== 'BOSS_REPLY') return undefined;
  const pending = context.pendingBossQuestion;
  if (pending === undefined) return undefined;
  if (event.questionId !== undefined && event.questionId !== pending.questionId) {
    return undefined;
  }
  return pending.resumeStateId;
}

/** Pending question and reply selected for one working leaf, if any. */
function continuationFor(context: ReviewContext, stateId: ReviewStateId) {
  const pending = context.pendingBossQuestion;
  if (pending === undefined || pending.resumeStateId !== stateId) return {};
  return {
    pendingBossQuestion: pending,
    ...(context.bossReply === undefined ? {} : { bossReply: context.bossReply }),
  };
}

function setPendingBossQuestion(
  event: unknown,
  params: {
    readonly stateId: ReviewStateId;
    readonly sourceItem: ReviewSourceItem;
    readonly roleId: ReviewRoleId;
  },
): PendingBossQuestion | undefined {
  const question = outputString(event, 'question');
  if (question === undefined || !outputGuard(event, 'needsBossReply')) {
    return undefined;
  }
  return {
    questionId: params.stateId,
    resumeStateId: params.stateId,
    sourceItem: params.sourceItem,
    asker: { kind: 'role', roleId: params.roleId },
    question,
  };
}

function clearBossReplyContext() {
  return { pendingBossQuestion: undefined, bossReply: undefined };
}

function bossInterrupts(ids: readonly ReviewStateId[]) {
  return ids.map(
    (id) =>
      ({
        guard: { type: 'canInterruptTo', params: { targetId: id } },
        target: `#${id}`,
        reenter: true,
        actions: 'abandonForInterrupt',
      }) as const,
  );
}

function resumableStates(ids: readonly ReviewStateId[]) {
  return ids.map(
    (id) =>
      ({
        guard: { type: 'resumesState', params: { stateId: id } },
        target: `#${id}`,
        reenter: true,
        actions: 'rememberBossReply',
      }) as const,
  );
}

function acceptedOutcome(
  source: ReviewStateId,
  target: string,
  outcome: string,
) {
  return {
    type: 'playbook.acceptedOutcome',
    params: { source, target, acceptedOutcome: outcome },
  } as const;
}

const machineSetup = setup({
  types: {} as {
    context: ReviewContext;
    events: ReviewEvent;
    input: ReviewInput;
    output: ReviewPlaybookOutput;
  },
  actors: {
    player: fromPromise<PlayerOutput, PlayerInput>(async () => {
      throw new Error('player actor must be provided by the runner');
    }),
  },
  guards: {
    isFindings,
    isClean,
    isCommitted,
    isRejectedAll,
    needsBossReply,
    validStartReview: ({ event }) =>
      event.type === 'START_REVIEW' && isNonEmptyString(event.callerInput),
    canInterruptTo: (
      { context, event },
      params: { readonly targetId: ReviewStateId },
    ) =>
      event.type === 'BOSS_INTERRUPT' &&
      event.targetId === params.targetId &&
      canEnter(context, params.targetId),
    emptyBossReply: ({ event }) =>
      event.type === 'BOSS_REPLY' &&
      (typeof event.answer !== 'string' || event.answer.trim().length === 0),
    resumesState: (
      { context, event },
      params: { readonly stateId: ReviewStateId },
    ) =>
      event.type === 'BOSS_REPLY' &&
      typeof event.answer === 'string' &&
      event.answer.trim().length > 0 &&
      resolvedQuestionId(context, event) === params.stateId &&
      canEnter(context, params.stateId),
  },
  actions: {
    'playbook.acceptedOutcome': (
      _args,
      _params: {
        readonly source: string;
        readonly target: string;
        readonly acceptedOutcome: string;
      },
    ) => undefined,
    startReview: assign(({ event }) => {
      if (event.type !== 'START_REVIEW') return {};
      return {
        callerInput: event.callerInput,
        reviewerOutput: undefined,
        latestCommit: undefined,
        coderOutput: undefined,
        coderOutcome: undefined,
        evaluatedRevision: undefined,
        lastError: undefined,
        ...clearBossReplyContext(),
      };
    }),
    abandonForInterrupt: assign(() => ({
      lastError: undefined,
      ...clearBossReplyContext(),
    })),
    rememberFindings: assign(({ event }) => ({
      reviewerOutput: outputString(event, 'reviewerOutput'),
      ...clearBossReplyContext(),
    })),
    rememberClean: assign(({ event }) => ({
      evaluatedRevision: outputString(event, 'evaluatedRevision'),
      ...clearBossReplyContext(),
    })),
    rememberCommitted: assign(({ event }) => ({
      latestCommit: outputString(event, 'latestCommit'),
      coderOutput: outputString(event, 'coderOutput'),
      coderOutcome: 'committed' as const,
      ...clearBossReplyContext(),
    })),
    rememberRejectedAll: assign(({ event }) => ({
      coderOutput: outputString(event, 'coderOutput'),
      coderOutcome: 'rejectedAll' as const,
      ...clearBossReplyContext(),
    })),
    rememberPendingQuestion: assign(
      (
        { event },
        params: {
          readonly stateId: ReviewStateId;
          readonly sourceItem: ReviewSourceItem;
          readonly roleId: ReviewRoleId;
        },
      ) => {
        const pending = setPendingBossQuestion(event, params);
        if (pending === undefined) {
          return {
            lastError: {
              name: 'Error',
              message: `${params.sourceItem} question output was malformed.`,
            },
            ...clearBossReplyContext(),
          };
        }
        return { pendingBossQuestion: pending, bossReply: undefined };
      },
    ),
    rememberBossReply: assign(({ event }) =>
      event.type === 'BOSS_REPLY' ? { bossReply: event.answer } : {},
    ),
    rememberEmptyBossReplyError: assign(() => ({
      lastError: {
        name: 'Error',
        message: 'BOSS_REPLY received an empty answer.',
      },
      ...clearBossReplyContext(),
    })),
    rememberActorError: assign(({ event }) => ({
      lastError: normalizeError(actorError(event)),
      ...clearBossReplyContext(),
    })),
    rememberMalformedPlayerOutput: assign(
      (_args, params: { readonly sourceItem: ReviewSourceItem }) => ({
        lastError: {
          name: 'Error',
          message: `Player result for ${params.sourceItem} did not match a declared outcome.`,
        },
        ...clearBossReplyContext(),
      }),
    ),
  },
});

export const reviewMachine = machineSetup.createMachine({
  id: 'review',
  initial: 'ready',
  context: {},
  output: ({ context }): ReviewPlaybookOutput => {
    if (!isNonEmptyString(context.evaluatedRevision)) {
      throw new Error(
        'REVIEW reached done without a receipt-observed evaluated revision',
      );
    }
    return {
      noUnsettledFindings: true,
      evaluatedRevision: context.evaluatedRevision,
    };
  },
  on: {
    BOSS_INTERRUPT: bossInterrupts(RESUMABLE_STATE_IDS),
  },
  states: {
    ready: {
      id: 'ready',
      description: STATE_DESCRIPTIONS.ready,
      meta: playbookMeta('ready'),
      tags: ['playbook.parked'],
      on: {
        START_REVIEW: {
          guard: 'validStartReview',
          target: 'reviewFirstRound',
          actions: 'startReview',
        },
      },
    },
    reviewFirstRound: {
      id: 'reviewFirstRound',
      description: STATE_DESCRIPTIONS.reviewFirstRound,
      meta: playbookMeta('reviewFirstRound', 'reviewer'),
      tags: ['playbook.busy'],
      invoke: {
        src: 'player',
        input: ({ context }): ReviewFirstRoundInput => ({
          stateId: 'reviewFirstRound',
          role: 'reviewer',
          sourceItem: 'REVIEW-1',
          prompt: REVIEW_FIRST_ROUND_PROMPT,
          result: REVIEW_FIRST_ROUND_RESULTS,
          callerInput: context.callerInput ?? '',
          ...continuationFor(context, 'reviewFirstRound'),
        }),
        onDone: [
          {
            guard: 'isFindings',
            target: 'fixFindings',
            actions: [
              acceptedOutcome('reviewFirstRound', 'fixFindings', 'findings'),
              'rememberFindings',
            ],
          },
          {
            guard: 'isClean',
            target: 'done',
            actions: [
              acceptedOutcome('reviewFirstRound', 'done', 'clean'),
              'rememberClean',
            ],
          },
          {
            guard: 'needsBossReply',
            target: 'awaitBossReply',
            actions: [
              acceptedOutcome(
                'reviewFirstRound',
                'awaitBossReply',
                'needsBossReply',
              ),
              {
                type: 'rememberPendingQuestion',
                params: {
                  stateId: 'reviewFirstRound',
                  sourceItem: 'REVIEW-1',
                  roleId: 'reviewer',
                },
              },
            ],
          },
          {
            target: 'failed',
            actions: {
              type: 'rememberMalformedPlayerOutput',
              params: { sourceItem: 'REVIEW-1' },
            },
          },
        ],
        onError: { target: 'failed', actions: 'rememberActorError' },
      },
    },
    fixFindings: {
      id: 'fixFindings',
      description: STATE_DESCRIPTIONS.fixFindings,
      meta: playbookMeta('fixFindings', 'coder'),
      tags: ['playbook.busy'],
      invoke: {
        src: 'player',
        input: ({ context }): FixFindingsInput => ({
          stateId: 'fixFindings',
          role: 'coder',
          sourceItem: 'REVIEW-2',
          prompt: FIX_FINDINGS_PROMPT,
          result: FIX_FINDINGS_RESULTS,
          callerInput: context.callerInput ?? '',
          reviewerOutput: context.reviewerOutput ?? '',
          ...continuationFor(context, 'fixFindings'),
        }),
        onDone: [
          {
            guard: 'isCommitted',
            target: 'reviewAfterCommit',
            actions: [
              acceptedOutcome('fixFindings', 'reviewAfterCommit', 'committed'),
              'rememberCommitted',
            ],
          },
          {
            guard: 'isRejectedAll',
            target: 'reviewAfterRejection',
            actions: [
              acceptedOutcome(
                'fixFindings',
                'reviewAfterRejection',
                'rejectedAll',
              ),
              'rememberRejectedAll',
            ],
          },
          {
            guard: 'needsBossReply',
            target: 'awaitBossReply',
            actions: [
              acceptedOutcome('fixFindings', 'awaitBossReply', 'needsBossReply'),
              {
                type: 'rememberPendingQuestion',
                params: {
                  stateId: 'fixFindings',
                  sourceItem: 'REVIEW-2',
                  roleId: 'coder',
                },
              },
            ],
          },
          {
            target: 'failed',
            actions: {
              type: 'rememberMalformedPlayerOutput',
              params: { sourceItem: 'REVIEW-2' },
            },
          },
        ],
        onError: { target: 'failed', actions: 'rememberActorError' },
      },
    },
    reviewAfterCommit: {
      id: 'reviewAfterCommit',
      description: STATE_DESCRIPTIONS.reviewAfterCommit,
      meta: playbookMeta('reviewAfterCommit', 'reviewer'),
      tags: ['playbook.busy'],
      invoke: {
        src: 'player',
        input: ({ context }): ReviewAfterCommitInput => ({
          stateId: 'reviewAfterCommit',
          role: 'reviewer',
          sourceItem: 'REVIEW-3',
          prompt: REVIEW_AFTER_COMMIT_PROMPT,
          result: REVIEW_AFTER_COMMIT_RESULTS,
          callerInput: context.callerInput ?? '',
          latestCommit: context.latestCommit ?? '',
          coderOutput: context.coderOutput ?? '',
          ...continuationFor(context, 'reviewAfterCommit'),
        }),
        onDone: [
          {
            guard: 'isFindings',
            target: 'fixFindings',
            actions: [
              acceptedOutcome('reviewAfterCommit', 'fixFindings', 'findings'),
              'rememberFindings',
            ],
          },
          {
            guard: 'isClean',
            target: 'done',
            actions: [
              acceptedOutcome('reviewAfterCommit', 'done', 'clean'),
              'rememberClean',
            ],
          },
          {
            guard: 'needsBossReply',
            target: 'awaitBossReply',
            actions: [
              acceptedOutcome(
                'reviewAfterCommit',
                'awaitBossReply',
                'needsBossReply',
              ),
              {
                type: 'rememberPendingQuestion',
                params: {
                  stateId: 'reviewAfterCommit',
                  sourceItem: 'REVIEW-3',
                  roleId: 'reviewer',
                },
              },
            ],
          },
          {
            target: 'failed',
            actions: {
              type: 'rememberMalformedPlayerOutput',
              params: { sourceItem: 'REVIEW-3' },
            },
          },
        ],
        onError: { target: 'failed', actions: 'rememberActorError' },
      },
    },
    reviewAfterRejection: {
      id: 'reviewAfterRejection',
      description: STATE_DESCRIPTIONS.reviewAfterRejection,
      meta: playbookMeta('reviewAfterRejection', 'reviewer'),
      tags: ['playbook.busy'],
      invoke: {
        src: 'player',
        input: ({ context }): ReviewAfterRejectionInput => ({
          stateId: 'reviewAfterRejection',
          role: 'reviewer',
          sourceItem: 'REVIEW-4',
          prompt: REVIEW_AFTER_REJECTION_PROMPT,
          result: REVIEW_AFTER_REJECTION_RESULTS,
          callerInput: context.callerInput ?? '',
          coderOutput: context.coderOutput ?? '',
          ...continuationFor(context, 'reviewAfterRejection'),
        }),
        onDone: [
          {
            guard: 'isFindings',
            target: 'fixFindings',
            actions: [
              acceptedOutcome('reviewAfterRejection', 'fixFindings', 'findings'),
              'rememberFindings',
            ],
          },
          {
            guard: 'isClean',
            target: 'done',
            actions: [
              acceptedOutcome('reviewAfterRejection', 'done', 'clean'),
              'rememberClean',
            ],
          },
          {
            guard: 'needsBossReply',
            target: 'awaitBossReply',
            actions: [
              acceptedOutcome(
                'reviewAfterRejection',
                'awaitBossReply',
                'needsBossReply',
              ),
              {
                type: 'rememberPendingQuestion',
                params: {
                  stateId: 'reviewAfterRejection',
                  sourceItem: 'REVIEW-4',
                  roleId: 'reviewer',
                },
              },
            ],
          },
          {
            target: 'failed',
            actions: {
              type: 'rememberMalformedPlayerOutput',
              params: { sourceItem: 'REVIEW-4' },
            },
          },
        ],
        onError: { target: 'failed', actions: 'rememberActorError' },
      },
    },
    awaitBossReply: {
      id: 'awaitBossReply',
      description: STATE_DESCRIPTIONS.awaitBossReply,
      meta: playbookMeta('awaitBossReply'),
      tags: ['playbook.parked'],
      on: {
        BOSS_REPLY: [
          {
            guard: 'emptyBossReply',
            target: '#failed',
            actions: 'rememberEmptyBossReplyError',
          },
          ...resumableStates(RESUMABLE_STATE_IDS),
        ],
        START_REVIEW: {
          guard: 'validStartReview',
          target: 'reviewFirstRound',
          actions: 'startReview',
        },
      },
    },
    failed: {
      id: 'failed',
      description: STATE_DESCRIPTIONS.failed,
      meta: playbookMeta('failed'),
      tags: ['playbook.parked'],
      on: {
        START_REVIEW: {
          guard: 'validStartReview',
          target: 'reviewFirstRound',
          actions: 'startReview',
        },
      },
    },
    done: {
      id: 'done',
      description: STATE_DESCRIPTIONS.done,
      meta: terminalMeta('done', 'success'),
      type: 'final',
    },
  },
});

export default reviewMachine;
