// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
// Generated by slc/materialize-link.mjs; governed by the complete slc/link.md.
// FSM: "./review.fsm.js"; export: reviewMachine; strategies: shared defaults with labelled string relays and nested actors.
import { reviewMachine as machine } from "./review.fsm.js";
import type { PlayerInput as SourcePlayerInput } from "./review.fsm.js";
import {
  createXStatePlaybookRuntime, snapshotJsonValue,
  composePlayerContinuation, type XStatePromptIdentity,
  type PlaybookPlayerInput,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
export type {
  PlayerResult,
  PlayerCallOptions,
  PlayerSessionStore,
  CaptainResult,
  CaptainCallOptions,
  JsonValue,
  NormalizedError,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookStateValue,
  PlaybookState,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookPorts,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookControlReceipt,
  PlaybookControlView,
} from '@sublang/playbook/runtime';

export interface PlaybookRuntimeOptions {

}
export type PlaybookHostCapabilities = XStatePlaybookRuntimeConstruction<
  PlaybookRuntimeOptions, { readonly authority: object }
>['hostCapabilities'];

const OPTION_SCHEMA = {} as const;
const INPUT_MAPPING = {} as const;
const RESUMABLE_STATE_IDS: ReadonlySet<string> = new Set([
  "firstReview",
  "answerFindings",
  "reviewFixCommit",
  "reviewAfterRejection"
]);
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([]);
const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  "reviewerOutput",
  "coderOutput"
]);
export function validateOptions(value: unknown): PlaybookRuntimeOptions {
  const captured = snapshotJsonValue(value === undefined ? {} : value, "REVIEW runtime options");
  if (captured === null || typeof captured !== 'object' || Array.isArray(captured)) {
    throw new TypeError("REVIEW runtime options must be an object");
  }
  const fields = captured as Readonly<Record<string, unknown>>;
  for (const key of Object.keys(captured)) {
    if (!Object.hasOwn(OPTION_SCHEMA, key)) throw new TypeError("REVIEW runtime options." + key + ' is not declared');
  }
  for (const [key, schema] of Object.entries(OPTION_SCHEMA) as [string, { type: string; required: boolean }][]) {
    if (!Object.hasOwn(captured, key)) {
      if (schema.required) throw new TypeError("REVIEW runtime options." + key + ' is required');
    } else if (typeof fields[key] !== schema.type || (schema.type === 'number' && !Number.isFinite(fields[key]))) {
      throw new TypeError("REVIEW runtime options." + key + ' must be a ' + schema.type);
    }
  }
  return captured as unknown as PlaybookRuntimeOptions;
}
function renderPlayerPrompt(input: SourcePlayerInput, promptIdentity: XStatePromptIdentity, resuming = false): string {
  const fields = input as unknown as Readonly<Record<string, unknown>>;
  const mapping: Readonly<Record<string, string>> = {};
  const identities: Readonly<Record<string, string>> = {"coder-llm":"coder","reviewer-llm":"reviewer"};
  const omitted = new Set<string>([]);
  const fieldFor = (token: string): string => Object.hasOwn(mapping, token) ? mapping[token]! : (token === '#' ? 'irNumber' : token.replace(/-([A-Za-z0-9_$])/g, (_match: string, next: string) => next.toUpperCase()));
  const parts = input.prompt.split(/(\r?\n)/);
  let body = '';
  for (let index = 0; index < parts.length; index += 2) {
    const line = parts[index]!;
    if (omitted.has(line)) {
      const token = /<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>$/.exec(line)![1]!;
      if (fields[fieldFor(token)] === '') continue;
    }
    body += line.replace(/<(#|[A-Za-z_$][A-Za-z0-9_$-]*)>/g, (match: string, token: string): string => {
      const value = Object.hasOwn(identities, token) ? promptIdentity(identities[token]!) : fields[fieldFor(token)];
      if (typeof value !== 'string') return match;
      return line.startsWith('> ') ? value.replace(/\r?\n/g, (ending: string) => ending + '> ') : value;
    }) + (parts[index + 1] ?? '');
  }
  return composePlayerContinuation(input, body, resuming);
}
const composePlayerPrompt = (input: PlaybookPlayerInput, promptIdentity: XStatePromptIdentity, resuming?: boolean): string =>
  renderPlayerPrompt(input as SourcePlayerInput, promptIdentity, resuming);
const runtimeSpec = {
  composePlayerPrompt,
  ...{
  "label": "REVIEW",
  "compat": {
    "artifactSchema": 3,
    "runtimeAbi": 1
  },
  "entryEvent": {
    "type": "START_REVIEW",
    "textField": "callerInput",
    "contextField": "callerInput"
  },
  "bossEvents": [],
  "roleStates": {
    "firstReview": {
      "role": "reviewer",
      "label": "Reviewer runs the first review round over the caller's review scope."
    },
    "answerFindings": {
      "role": "coder",
      "label": "Coder accepts or rejects each of Reviewer's findings, fixing accepted ones in one new review-fix commit."
    },
    "reviewFixCommit": {
      "role": "reviewer",
      "label": "Reviewer runs the next review round over the cumulative committed state after the latest review-fix commit."
    },
    "reviewAfterRejection": {
      "role": "reviewer",
      "label": "Reviewer runs the next review round after Coder rejected every finding without a new commit."
    }
  },
  "outcomeAuthority": {
    "governedPlayerStates": {
      "firstReview": {
        "findings": {
          "fields": {
            "reviewerOutput": "presentation"
          },
          "repositoryDisposition": "unchanged"
        },
        "clean": {
          "fields": {
            "evaluatedRevision": "effect"
          },
          "repositoryDisposition": "unchanged"
        },
        "needsBossReply": {
          "fields": {
            "question": "presentation"
          },
          "repositoryDisposition": "unchanged"
        }
      },
      "answerFindings": {
        "committed": {
          "fields": {
            "latestCommit": "effect",
            "coderOutput": "presentation"
          },
          "repositoryDisposition": "one-descendant-commit"
        },
        "rejectedAll": {
          "fields": {
            "coderOutput": "presentation"
          },
          "repositoryDisposition": "unchanged"
        },
        "needsBossReply": {
          "fields": {
            "question": "presentation"
          },
          "repositoryDisposition": "deferred"
        }
      },
      "reviewFixCommit": {
        "findings": {
          "fields": {
            "reviewerOutput": "presentation"
          },
          "repositoryDisposition": "unchanged"
        },
        "clean": {
          "fields": {
            "evaluatedRevision": "effect"
          },
          "repositoryDisposition": "unchanged"
        },
        "needsBossReply": {
          "fields": {
            "question": "presentation"
          },
          "repositoryDisposition": "unchanged"
        }
      },
      "reviewAfterRejection": {
        "findings": {
          "fields": {
            "reviewerOutput": "presentation"
          },
          "repositoryDisposition": "unchanged"
        },
        "clean": {
          "fields": {
            "evaluatedRevision": "effect"
          },
          "repositoryDisposition": "unchanged"
        },
        "needsBossReply": {
          "fields": {
            "question": "presentation"
          },
          "repositoryDisposition": "unchanged"
        }
      }
    }
  },
  "placeholderFields": {},
  "transitionEventFields": [
    "callerInput",
    "targetId",
    "answer",
    "questionId"
  ],
  "controlContextFields": []
},
  snapshotOptions: validateOptions,
  machineInput: (options: PlaybookRuntimeOptions) => Object.fromEntries(
    Object.entries(INPUT_MAPPING).filter(([, key]) => options[key as keyof PlaybookRuntimeOptions] !== undefined)
      .map(([field, key]) => [field, options[key as keyof PlaybookRuntimeOptions]]),
  ),
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  resumableStateIds: RESUMABLE_STATE_IDS,
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
} satisfies XStatePlaybookRuntimeSpecV3<PlaybookRuntimeOptions>;

export const _internal = {
  composePlayerPrompt,
  RESUMABLE_STATE_IDS,
  UNFINISHED_FINAL_STATE_IDS,
  VERBATIM_PAYLOAD_FIELDS,
};
const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<PlaybookRuntimeOptions, PlaybookHostCapabilities>, 3
> = createXStatePlaybookRuntime<PlaybookRuntimeOptions, PlaybookHostCapabilities>(machine, runtimeSpec);
export default createPlaybookRuntime;
